### ISSUE TITLE
Update QueryPropertyMarker/QueryPropertyMarkerVisitor to return the classes it finds

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#1022]
Instead of passing in a class type to the QueryPropertyMarkerVisitor, we should update it to just return all of the QueryPropertyMarker instances that it finds for a given node.  Then we can make a determination based on what it finds.  This will also discourage people from making multiple instanceOf calls back to back against a single node.  

We should also consider creating a specific method which determines whether the node is a delayed node as we will soon have more than just delayed property markers with the new BoundedRange marker.

**Comment by lbschanno** [comment]
@jwomeara are you saying that you want the QueryPropertyMarkerVisitor to examine a full JEXL query and return every QueryPropertyMarker instance it finds? e.g., given the following query:

`((BoundedRange = true) && (FOO > 1 && FOO < 10)) && ((ASTDelayedPredicate = true) && (FOO == 'val'))`

you would want the QueryPropertyMarkerVisitor to return a list of the classes BoundedRange.class and ASTDelayedPredicate.class, and the source nodes `(FOO > 1 && FOO < 10)`, `(FOO == 'val')`? 

Or do you want it to keep the same logic, but return a result object that contains the identified marker class (if one is found) and the associated source node with an API to allow multiple instanceOf determinations made against the result object itself without needing to use the QueryPropertyMarkerVisitor again for the same node? e.g. something like the following:

```java
QueryPropertyMarker.Instance instance = QueryPropertyMarkerVisitor.getInstance(node); // Use the QueryPropertyMarkerVisitor only once
if(instance.isInstanceOf(BoundedRange.class)) { // Perform multiple subsequent operations on the Instance object.
    return instance.getSourceNode(); // Return source JexlNode.
} else if (instance.isAnyInstanceExcept(ASTDelayedPredicate.class)) {
    instance.getSourceNode().jttAccept(thisVisitor, data);
}
```

Additionally there is one thing that's confusing to me. After looking at the QueryPropertyMarkerVisitor, it indicates that it's possible for a single query property marker to have multiple source nodes, i.e. `((MarkerType = true) && (source) && (source))`. Is this true? All of the examples I've seen thus far only had one source node.

**Comment by lbschanno** [comment]
Disregard that last question where I was confused.

**Comment by ivakegg** [comment]
I am not exactly sure what he was getting at here.  I am guessing he is referring to removing the isInstance calls and instead have one method that returns the type (as a class or enum) that can be used in a case statement.  I this what you mean @jwomeara ?

**Comment by lbschanno** [comment]
@ivakegg I have PR #1048 submitted for this that I think should address all of @jwomeara's concerns.
