### ISSUE TITLE
Update Execution service to modify result limit by DN

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1028]
Similar to #1027, we should allow configuring query logics to allow different result limits based on DN.  Hence the BaseQueryLogic need a new member which maps DNs to result limits.  Then the query execution should take this into account (in RunningQuery I think) when applying the maxResults limit.

**Comment by lbschanno** [comment]
@ivakegg should the DNs to result limits be ignored if maxResultsOverride is set?
