### ISSUE TITLE
Quickstart / Accumulo 2.x deployment is broken on master branch

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#1036]

**Comment by ivakegg** [comment]
This may be somewhat covered by #533

**Comment by ivakegg** [comment]
ceellis added this to #533:

Noted the following exception when running the datawave quickstart tests:

ERROR [datawave.query.tables.ScannerSession] (default task-1) [cn=test a. user, ou=example developers, o=example corp, c=us] [a23bb2a5-f929-4424-a92f-2bf028d63c51] Exception discovered on hasNext call: java.lang.ClassCastException: datawave.webservice.common.connection.WrappedAccumuloClient cannot be cast to org.apache.accumulo.core.clientImpl.ClientContext
at datawave.query.scheduler.PushdownFunction.binRanges(PushdownFunction.java:180)
at datawave.query.scheduler.PushdownFunction.redistributeQueries(PushdownFunction.java:145)
at datawave.query.scheduler.PushdownFunction.apply(PushdownFunction.java:84)
at datawave.query.scheduler.PushdownFunction.apply(PushdownFunction.java:45)
at com.google.common.collect.Iterators$5.transform(Iterators.java:757)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
at datawave.query.tables.BatchScannerSession.run(BatchScannerSession.java:284)
at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
at java.lang.Thread.run(Thread.java:748)

**Comment by ceellis** [comment]
Another minor issue:  allStatus or accumuloStatus report that only gc is running and that master, monitor, tracer, and tserver are not running.  This is incorrect as those service ARE in fact, running as shown by the 'jps' command.

**Comment by keith-ratcliffe** [comment]
Currently, the issue-1036 branch incorporates upgrade to Accumulo 2.0.1, and also webservice module classpath update to fix the deployment failure

@ceellis , the stacktrace you observed is the next big issue to tackle. 

@ivakegg @jwomeara , I believe the fix for that will involve some combination of the following: 
- Merging changes from [here](https://github.com/NationalSecurityAgency/datawave/pull/967)
- Re-incorporating some of the changes from 9e418e5, which we had reverted due to the performance issue that surfaced (re: #850)
- Possibly others

**Comment by keith-ratcliffe** [comment]
@ceellis I think my current changes should resolve the other issue(s) you observed

**Comment by keith-ratcliffe** [comment]
> ...I believe the fix for that _might_ involve some combination of the following:
> 
> * Merging changes from [here](https://github.com/NationalSecurityAgency/datawave/pull/967)
> * Re-incorporating some of the changes from [9e418e5](https://github.com/NationalSecurityAgency/datawave/commit/9e418e5974eece0958ffbc6b3324fe2250cff3b9), which we had reverted due to the performance issue that surfaced (re: #850)
> * Possibly others

Fortunately, these predictions did not prove true. Fixes were simple. See PR #1040

**Comment by thebikerdude** [comment]
@keith-ratcliffe Drew recommended that I continue to help test the 2.x deployment and any issues you fix.  Once these changes have been merged to master, I can pull them down and rerun the test I did.  Any other things I can look at/work on in the interim?

**Comment by keith-ratcliffe** [comment]
> @keith-ratcliffe Drew recommended that I continue to help test the 2.x deployment and any issues you fix. Once these changes have been merged to master, I can pull them down and rerun the test I did. Any other things I can look at/work on in the interim?
If you pull the issue-1036 branch and test out those changes, that would be helpful. I'll may have another fix or two coming soon as well

**Comment by keith-ratcliffe** [comment]
I did discover another issue, which is that any ingest scripts where we invoke our own java code via `$ACCUMULO_HOME/bin/accumulo datawave.ingest.SomeClass ...` are broken due to classpath issues. The `create-shards-since.sh` script is one example

In Accumulo 1.x, there was support for adding jars to the accumulo classpath inline as needed. E.g.,...
```
$ACCUMULO_HOME/bin/accumulo -add $LIST_OF_JARS datawave.ingest.SomeClass ...
```
But 2.x removed that functionality. To fix, it looks like we'll either need to add **datawave-ingest-home/lib/*** to the accumulo classpath by editing the deployed **$ACCUMULO_HOME/conf/accumulo-env.sh** or we'll need to discontinue use of the bin/accumulo script for executing our code

**Comment by thebikerdude** [comment]
@keith-ratcliffe  The issue-1036 branch deployed and installed cleanly and datawaveWebTest passed.

However, accumuloStatus still says master, monitor, tracer, and tserver are not running when they actually are.

**Comment by keith-ratcliffe** [comment]
> @keith-ratcliffe The issue-1036 branch deployed and installed cleanly and datawaveWebTest passed.
> 
> However, accumuloStatus still says master, monitor, tracer, and tserver are not running when they actually are.

@thebikerdude Thanks for catching that (again)! My latest commit fixes that bug
