### ISSUE TITLE
UNIQUE functions appears to be dropping results with missing fields

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1063]
Initially the UNIQUE function was written to return unique instances of results given a set of fields.  It has been observed lately that results with missing fields are not being considered as unique.  Note that this may not be deterministic and hence we may have a threading/yielding issue that is resulting in this observation.  One example of a query with this problem was as follows:

(FIELD1:value1 AND (#ISNOTNULL(FIELD2) OR (#ISNOTNULL(FIELD3) AND (#ISNOTNULL(FIELD4) OR #ISNOTNULL(FIELD5)))) AND (#UNIQUE(FIELD4))

Without the #UNIQUE this returned 1 result where FIELD4 was empty/null.  With the #UNIQUE, this returned 0 results.

**Comment by friedlou** [comment]
I would like to work this issue.
