### ISSUE TITLE
Remove code paths for type metadata in hdfs

### ISSUE THREAD

**Issue by hlgp** [NationalSecurityAgency/datawave#1092]
Until we're able to identify the leak, rip out the typemetadata in hdfs logic and use only the direct accumulo path.

**Comment by keith-ratcliffe** [comment]
Dup of [#1076](https://github.com/NationalSecurityAgency/datawave/issues/1076)?

**Comment by hlgp** [comment]
Ah, yes.  Except for the part about feature not being used anymore as it was still very active in production today...sort of.  Though reading your note in #1049, "So, if the static typeMetadataProvider field fails to initialize there as expected, the Factory here will continuously allocate new ClassPathXmlApplicationContext instances, and those will accumulate indefinitely on any threads that trigger this code path" maybe fixing that will do the trick.  In any case the actual update mechanism broke several years ago, so I'm still in favor of nuking it.  Closing as dupe.
