### ISSUE TITLE
shardIndex UIDs not being updated correctly in the UID.LIST

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1107]
There is one known issue related to UID counts not being updated correctly:

case 1: uid0 is added twice to an empty UID list: the count becomes 2 when it should be 1
case 2: uid0 is added twice to a maxed out UID list: the count is incremented by 2 when it should be incremented only by 1

In addition to this we have seen evidence where the UIDS in the UID_LIST are not being removed correctly either when delete mutations are added.

The UID.LIST needs to be updated to ensure counts and UID lists are updated correctly in all scenarios.

**Comment by friedlou** [comment]
I would like to work on this.

**Comment by ivakegg** [comment]
This may be covered by #1173 or visa versa.

**Comment by friedlou** [comment]
Did some investigation. Followed the flow of unit tests for both GlobalIndexUidAggregator and UID.LIST (newly developed for this purpose).
Concluded that issues raised in the ticket is more associated with GlobalIndexUidAggregator and was already fixed. However, UID.LIST should have it's own unit test. Will continue develop and suite of tests, as priority allows.

**Comment by friedlou** [comment]
OBE
