### ISSUE TITLE
occurrence function not working as expected

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1108]
The occurence query function (#OCCURANCE) is not correct because of a couple of reasons:
1) Values are added into the JexlContext from the index as well as those from the event.  Only the values from the event should be considered in this case unless there are none.
2) The loop that tries to count the occurences is invalid in that it tries to create a map based on type, but then increments the count anyway for those that do not have a type.  Basically a somewhat random function based on the order of the values in the set.

**Comment by lbschanno** [comment]
@ivakegg I'm interested in working on this. Where is the logic for this taking place? I didn't see it in the `OccurrenceFunction` class.

**Comment by ivakegg** [comment]
Query functions are found in several classes.  For this function look in datawave.query.jexl.functions.  The occurance methods are at the top of the class.  In a lucene query the #OCCURANCE function will be turned into a filter:occurance() jexl function.  When a query is evaluated in the JexlEvaluation class, Jexl will pass in the field values from the jexl context as the first parameter of that function.  The issue is that we currently do not have a way to distinguish values in the Jexl context that were derived from the index vs the event fields themselves.  Also the getSizeOf(Iterable<?> iterable) method in the EvaluationPhaseFilterFunctions class is kinda hokey to start with.

The JexlContext is built when calling the visit method on the Document.  Attributes that are added to the Document need to be marked as being from the index vs the event as well as the ValueTuple objects which are put into the Jexl context.
