### ISSUE TITLE
datadictionary link broken in quickstart guide

### ISSUE THREAD

**Issue by abazabaaa** [NationalSecurityAgency/datawave#1120]
https://code.nsa.gov/docs/2.9/getting-started/data-model#data-dictionary-table

I also can't seem to access the data dictionary in the localhost browser:

https://localhost:8843/dictionary/data/v1/

![image](https://user-images.githubusercontent.com/66654563/111917123-85f40f00-8a3b-11eb-8562-31a9f791a907.png)

**Comment by foster33** [comment]
The current Data Dictionary [link](https://code.nsa.gov/datawave/docs/6.x/getting-started/data-model#data-dictionary-table) within the quickstart guide is not broken. So this issue can be closed.

As for the localhost data dictionary part, I recommend referring to the [docker README](https://github.com/NationalSecurityAgency/datawave/blob/feature/queryMicroservices/docker/README.md). This will help get you up and running. I know this is old at this point, but if anyone else ever stumbles across this, hopefully that helps.
