### ISSUE TITLE
Link the table structures on the front readme or documentation

### ISSUE THREAD

**Issue by phrocker** [NationalSecurityAgency/datawave#12]
I think it would be beneficial to place the table structures on the front readme or linked in the docs. I know the docs are under construction, but I'd be happy to take a first stab at this.

**Comment by phrocker** [comment]
I'll be glad to submit a PR against the ReadMe, with input from anyone to correct my mistakes.

**Comment by tomnelson** [comment]
I'd like to see this. Thanks!

**Comment by keith-ratcliffe** [comment]
I second that! Thanks

**Comment by drewfarris** [comment]
For what it's worth, there is a version of this that will be reviewed to release.

**Comment by phrocker** [comment]
@drewfarris That's great. do you have it available?

**Comment by keith-ratcliffe** [comment]
Data model and other docs are available at https://code.nsa.gov/datawave/docs which is linked on the home page of this repo
