### ISSUE TITLE
content phrase function ambiguity when field is missing

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1269]
The phrase functions in the content functions class are ambiguous when the field does not exist in the JexlContext.  In particular:

phrase(Object, Map, ...)
phrase(Float, Map, ...)
phrase(Iterable, Map, ...)

The jexl interpreter can handle having the Iterable and Object versions, but the addition of the Float instance confuses the issue.  The Float instance needs to be subsumed under the Object version of the method.

**Comment by keith-ratcliffe** [comment]
> The phrase functions in the content functions class are ambiguous when the field does not exist in the JexlContext. In particular:
> 
> phrase(Object, Map, ...)
> phrase(Float, Map, ...)
> phrase(Iterable, Map, ...)
> 
> The jexl interpreter can handle having the Iterable and Object versions, but the addition of the Float instance confuses the issue. The Float instance needs to be subsumed under the Object version of the method.

Related I think, at least in part, to #1204 (PR #1209)
