### ISSUE TITLE
Range stream misses shards edge case

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1364]
query && ((function && (SHARDS_AND_DAYS = 'X,Y,Z')) || (function && (SHARDS_AND_DAYS = 'X,Y,Z')))
where X,Y, and Z are days
All of the actually documents are in Z, but it only returns ranges for the first shard in Z.

Interestingly the following variants succeed in finding all of the ranges:
query && ((function && (SHARDS_AND_DAYS = 'Z')) || (function && (SHARDS_AND_DAYS = 'Z')))
query && ((function && (SHARDS_AND_DAYS = 'X,Z')) || (function && (SHARDS_AND_DAYS = 'X,Z')))

**Comment by FineAndDandy** [comment]
This was broken by #1336 It appears different use cases require next() to advance and not advance with each call...
