### ISSUE TITLE
RfileInputFormat question

### ISSUE THREAD

**Issue by roshanp** [NationalSecurityAgency/datawave#145]
I did not see a mailing list? is there one available?

If not, I had a question about the MultiRfileInputFormat. Is that something you would recommend using? I see that it queries the Metadata table to get the appropriate rfiles; however, what happens if there is a compaction during the job run. If the rfile gets deleted or renamed, etc? Is there a way to protect the input format from that?

I like the idea of going against the rfiles directly to remove some of the load away from the tablet servers, would you guys recommend this approach?

**Comment by drewfarris** [comment]
Hi Roshan,

No mailing list at this point, probably a good idea though.

When I use the MultiRfileInputFormat I typically use it against a table that's cloned from the original and taken offline. Cloning a table in Accumulo is a relatively inexpensive operation - it only clones the metadata (splits, and file references). The original table will live out its life and eventually drift away from the offline clone throughout the course of writes and compaction etc. The offline clone will continue to reference the rfiles from the original table at the point in time it was cloned. When the offline clone is dropped, those rfiles no longer be referenced by the original table will be garbage collected. Just don't forget to delete your clones when the job is done.

If I recall correctly, MultiRfileInputFormat will still work against online tables, but I can't recall the semantics off the top of my head (re: tables changing, compactions, etc..).
