### ISSUE TITLE
[discuss] GitHub Wiki for Documentation?

### ISSUE THREAD

**Issue by drewfarris** [NationalSecurityAgency/datawave#15]
Do we want to use the GitHub wiki capabilities for documentation, or do we want all documentation to be checked in alongside the codebase? (https://github.com/NationalSecurityAgency/datawave/wiki)

**Comment by phrocker** [comment]
There's probably some healthy balance. On one hand some documentation is better suited for the GH wiki, but other documentation is likely better in the codebase. For example, the other ticket regarding table structures...I see something like that being useful in both forms with one perhaps providing a deeper dive? I would like to see some information available offline in a readme in markup because when I download code that's what I automatically open before I visit a wiki.

**Comment by keith-ratcliffe** [comment]
I don't think an official decision has been made at this point, but I'm currently experimenting locally with a Jekyll-based, static site for the github.io project site, which could be used for as much or as little documentation as we'd like in the end. Hope to have a beta version of it ready next week with minimal content and features, just so folks can evaluate and weigh in

@phrocker , if you were thinking standard markdown for the table structures doc, that would fit nicely with either paradigm really...ie, external (Jekyll) or internal docs

**Comment by jwomeara** [comment]
I feel like the readmes are good for people who like to peruse the code.  It can also be good if you're new and trying to learn about a particular component of datawave (or if you're a dev it's a nice place to explain a particular component of datawave).  It's nice that the info you need will be collocated with the modules you'll be working with.  

I would imagine that people who go to the IO page are primarily looking for a quick overview, but it could also include guides, links build artifacts, or more in-depth documentation/javadoc.  I could see that becoming the overall landing page for people who are interested in learning about datawave.  I think GeoWave's io page is a decent example: https://locationtech.github.io/geowave/

For the wiki, I feel like most of the wikis I've visited tend to be out of date with the main project.  The wiki isn't tied to a branch on your repo or anything like that, so I think it tends to be neglected, or at the very least tends to lag behind the main project by a bit.  Mapnik has a decent wiki, but even that lags behind a bit: https://github.com/mapnik/mapnik/wiki
