### ISSUE TITLE
Tests failing due to common temp folder usage

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#150]
A few of our tests are using junit's TempFolder to create a working folder while the test is running.  We occasionally run into issues where two tests are using the same folder, which causes a race condition.  This is due to the fact that TempFolder is creating folders named via a pseudo random number.  This has been causing some tests to fail intermittently.

**Comment by brianloss** [comment]
Looks like maybe this was fixed in a newer junit version: https://github.com/junit-team/junit4/issues/1223

**Comment by jwomeara** [comment]
Looks like it's going to be in their next release, 4.13.

**Comment by jwomeara** [comment]
Here's the ticket junit used to track this issue: https://github.com/junit-team/junit4/issues/1223
