### ISSUE TITLE
datawave-quickstart needs to work with openssl 3.x as well as openssl 1.x

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#1573]
Apparently the parameters that we are using to generate the various certificate variants during the datawaveWebTest will not work with openssl 3.x.  We should allow the scripts to work with the different versions of openssl.

**Comment by keith-ratcliffe** [comment]
Thanks for taking on this issue, @kevinrr888 !

For posterity...
Users with OpenSSL 3.x will encounter errors [here](https://github.com/NationalSecurityAgency/datawave/blob/a421eb747401985bb1aa517dba4db096d00f8366/contrib/datawave-quickstart/bin/query.sh#L470), causing `datawaveWebTest` to fail all tests

Unfortunately, the query.sh script obscures the actual error, but bash debugging revealed that the command on line 470 was failing with...
```
...
Error outputting keys and certificates
401767A5287F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```
