### ISSUE TITLE
Update datawave-quickstart to work with Python 2.X and 3.X

### ISSUE THREAD

**Issue by foster33** [NationalSecurityAgency/datawave#1609]
Currently, in step 4 of the 'Ingest Basics' part of the DataWave Tour there is a bug that does not allow for users to be using Python 3.X.

When users using Python 3.X do `./ingest-tv-shows.sh --download-only --outfile ~/more-tv-shows.json`, they get the following error:

```
[DW-INFO] - Downloading show data: 'Veep'
  File "<string>", line 1
    import sys,json;data=json.loads(sys.stdin.read()); print json.dumps(data, indent=2, sort_keys=True)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by keith-ratcliffe** [comment]
Good catch @foster33 
I noticed we have the same bug in `contrib/datawave-quickstart/bin/query.sh` [here](https://github.com/NationalSecurityAgency/datawave/blob/4019a3cefd67aaab81f8bc67b99f9ec0288e4936/contrib/datawave-quickstart/bin/query.sh#L136), but in reverse. That is, it'll work with 3x, but not 2x.

The same solution should suffice for both places, so if you wouldn't mind fixing it there too, that'd be great. If you do that, just change the issue title here to be "_Update datawave-quickstart to work with Python 2.X and 3.X_" , no need to create a second ticket, unless you want to
