### ISSUE TITLE
ConcurrentModificationException is thrown when closing ScannerFactory in ShardQueryLogic

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#1746]
In ShardQueryLogic.close() when creating a new array list from ScannerFactory.currentScanners() or ScannerFactory.currentSessions() it is possible that a ConcurrentModificationException will be thrown.  The creation of the new array list causes us to iterate over the elements of the set, which could (and is) still being modified when ScannerFactory.close() is called.  ScannerFactory.close() is not synchronized, so it is able to modify the set while other synchronized methods are acting on the set.  

Also, while ScannerFactory.currentSessions() does return an unmodifiable set, the underlying set is still modifiable, so this doesn't really do anything to protect against a race condition.  

We could solve this by making ScannerFactory.close() synchronized, and by updating ScannerFactory.currentScanners() and ScannerFactory.currentSessions() to return a NEW set when they are called, instead of the original set.

**Comment by aaronplee** [comment]
I don't know how you're doing this currently; you should absolutely think or consider DataInput and DataOutput streams. Utilize them; maybe a ByteBuffer wrap; also cut down significantly with processing if you transfer the data in byte[]. Unless you're already doing that. I just cloned the repo, so I'll take a gander. No harm in helping you all out.
