### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#206]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project **metrics-reporter: Compilation failure**
[ERROR] ....**/metrics-reporter/src/main/java/datawave/metrics/StatsDClient.java:[26,69]** cannot infer type arguments for java.lang.ThreadLocal<T>
[ERROR]   reason: **cannot use '<>' with anonymous inner classes**

Looks like this commit is the culprit: 56e1fd8a18c45d87a0dcb0a36bb088a792bef645

**Comment by brianloss** [comment]
I fixed in 5538cbf9665630d5deedac5c1cd4f1432272a4ca
