### ISSUE TITLE
Where O where did my Error Code go

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#2340]
We are no longer placing error codes in our metrics when using the federated query logic (CompositeQueryLogic).  E.g. if a query "times out" then the error code should be 500-27.

**Comment by lbschanno** [comment]
Reopening issue. Error codes are still missing from metrics. Details from a conversation with Ivan:

> Unfortunately I think we need to go back to the drawing board on the "where or where did my error codes go"
> (https://salmonrunworkspace.slack.com/archives/DL3L3P9SS/p1720728510515859)
> I was testing it out and managed to get some more info on what was actually getting missed
> They are on the create call, not necessarily the next call.
> So if you have a composite query logic, and the underlying query logic fails because of a syntax error, I think they expect a 500-7.  The response supposedly contains that error code, but the query metrics do not reflect that. (edited) 
> (https://salmonrunworkspace.slack.com/archives/DL3L3P9SS/p1720728663046249)
> We should be able to reproduce this fairly easily.
> Another error would be 400-16 when "The query contained fields which do not exist in the data dictionary".  That should be another one easy to reproduce

**Comment by lbschanno** [comment]
Closing ticket. The bug appeared on 7.0.7, and the repo at that tag did not have the bugfix commit in it. I confirmed that applying the bug fix did fix the issue with error codes not appearing metrics. Created tickets #2485 and #2486 to address areas of improvements that can be made for recording error codes to metrics.
