### ISSUE TITLE
CountingShardQueryLogic performance

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#2401]
Currently the CountingShardQueryLogic does an event query and simply counts the results in the transformer on the webserver side.  This could be done significantly better by creating counts on the tserver side.  Each range should results in 1 count document being returned to the webserver which the would total up those counts.

**Comment by lbschanno** [comment]
@ivakegg this is possibly already implemented. See the following in `CountingShardQueryLogic,getScheduler()`:

```java
    @Override
    public Scheduler getScheduler(ShardQueryConfiguration config, ScannerFactory scannerFactory) {
        PushdownScheduler scheduler = new PushdownScheduler(config, scannerFactory, this.metadataHelperFactory);
        scheduler.addSetting(new IteratorSetting(config.getBaseIteratorPriority() + 50, "counter", ResultCountingIterator.class.getName()));
        return scheduler;
    }
```

ResultCountingIterator returns a single entry after counting all the k/v pairs returned by the iterator beneath it on the stack. The transformer then aggregates the counts returned from this iterator. This seems to satisfy the requirements of this ticket, but if I am wrong here, please let me know.

**Comment by ivakegg** [comment]
Oh shoot.  It appears you are absolutely correct.  I should have verified the ticket for assigning it.  I am so sorry guys.

**Comment by ivakegg** [comment]
OBE
