### ISSUE TITLE
General ingest script cleanup, refactoring, and related issues

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#242]
This is by no means an exhaustive list of tasks, so if you have additional items of interest (or disagreement with any below) please share them here
 
* Standardization
  * When appropriate, refactor copied/duplicate code into function libraries that can be shared and sourced as needed
  * Use consistent look/feel and logic for help/usage and console logging
  * Use consistent approach for error handling for easier debugging, etc
  * Reformat code to use 2 spaces for indentation

* Readability
  * Use comments and/or aptly-named functions when appropriate, i.e., for blocks of code where the intent is not immediately apparent
  * If a script is more than a few lines long, add comment(s) and/or usage function to the top of the script to describe the purpose, any inputs, and any assumptions made by the script which may not be apparent to the user
   * Break up excessively long commands across lines via \
   * Rename certain bash variables to clarify their puspose. E.g.,
     * USERNAME / PASSWORD
     * WAREHOUSE_INSTANCE_NAME / INGEST_INSTANCE_NAME
     * WAREHOUSE_HADOOP_CONF / INGEST_HADOOP_CONF
     * INGEST_HOST

* Misc
  * See #241
  * Replace "$THIS_DIR" resolution logic with equivalent, portable bash logic that doesn't rely on python and on specific uname outputs
  * Remove any dead code, unused variables, etc. E.g., 
    * KEYSTORE* / TRUSTSTORE*

**Comment by keith-ratcliffe** [comment]
@bmwmaestoso not sure if this addresses all the issues you and I had discussed. If not, feel free to add/edit

**Comment by bmwmaestoso** [comment]
I think this covers most everything. But I would possibly like to see some additions such as:

- testing of command return status and perform necessary actions
- validation of function input parameters, terminate upon invalid condition
- provide ability to trace execution without having to use "set -x", which can be overload
  - options to allow verbose output for each function start/end, display parameters to function
  - methods to allow debug information, method checks to see if verbose mode has been set
  - trace mode that provides detail execution information (would also include debug info)

**Comment by keith-ratcliffe** [comment]
Closing, as it would be better to tackle most of these subtasks as separate tickets
