### ISSUE TITLE
faulty logic in MetadataTableSplitsCacheStatus  causes NPE

### ISSUE THREAD

**Issue by bmwmaestoso** [NationalSecurityAgency/datawave#248]
The file [MetadataTableSplitsCacheStatus.java](https://github.com/NationalSecurityAgency/datawave/blob/master/warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/job/MetadataTableSplitsCacheStatus.java) only contains a single method but it produces an NPE if the variable fileStatus is not set in a try/catch block. The method should should probably not have a try/catch block since it throws an IOException in the signature.

**Comment by jzgithub1** [comment]
I will look at this.
