### ISSUE TITLE
FieldIndexOnlyQueryIterator does not handle compressed documentOptions

### ISSUE THREAD

**Issue by FineAndDandy** [NationalSecurityAgency/datawave#258]
In FieldIndexOnlyQueryIterator.createAndSeekIndexIterator() the NON_INDEXED_DATATYPES are not decompressed if QueryOptions.QUERY_MAPPING_COMPRESS is set to true

**Comment by hkeebler** [comment]
@timg-dev are you working on this?  otherwise I'm looking for a "good first issue" to work.

**Comment by timg-dev** [comment]
A pull request was created and merged for this issue, so I am going to mark it closed. Thanks.
