### ISSUE TITLE
Broken link in Docker README

### ISSUE THREAD

**Issue by foster33** [NationalSecurityAgency/datawave#2587]
There is a broken link within the Docker Readme.

It can be seen [here](https://github.com/NationalSecurityAgency/datawave/blob/ce4a5de9112157314b5447722c51fe86f4825ef0/docker/README.md?plain=1#L211C1-L211C199) when linking to the Datawave Quickstart Readme.

The link should be updated to point to the right location.

**Comment by skyler-kv** [comment]
I'd like to work on this issue
