### ISSUE TITLE
Remove fixed length UID parse assumptions from TLDEventDataFilter

### ISSUE THREAD

**Issue by FineAndDandy** [NationalSecurityAgency/datawave#30]
TLDEventDataFilter assumes a 20 character fixed length base UID for rootPointer parsing purposes. This is not always the case. Adjust the code remove the bad assumption and instead calculate the length for each Key, counting the separators to determine root document state.

**Comment by phrocker** [comment]
The original design was to calculate the length, but doing so incurs cost across all keys. Considering that it's a filter, it will go against the keys for event evaluation. Could go back and run google benchmark to have a warm and fuzzy about the cost. Looking at the code it's definitely a poor assumption, but it looks like it's using 20 as a starting point to see if there are if there are additional periods after the base. Is there structure that includes additional periods even when it is a root?

**Comment by FineAndDandy** [comment]
At least in the context of Event Data we can make assumptions based on the length of the ColumnFamilyData and the previously parsed state. I don't see a way around parsing it for TF/FI

**Comment by phrocker** [comment]
ah cool so you guys are using vari length uids...make sense to make this ticket. I did a calculation on parsing the keys versus skipping and saw a 17% slow down on 500M keys. If you have a min length that might be better than nothing...just a thought.

**Comment by FineAndDandy** [comment]
Interesting. I actually saw a much smaller slowdown when iterating over the
UID of the key (for events) only 7% on 100M keys. Using the assumptions
above at least for event keys I think we will see a net increase in
performance.
