### ISSUE TITLE
Add ability to alias indexed fields

### ISSUE THREAD

**Issue by hlgp** [NationalSecurityAgency/datawave#31]
Add the ability to store the alias at ingest rather than be expanded via query model, reducing index scans.  Trade storage for performance.

**Comment by drewfarris** [comment]
It might be nice to be able configure different tokenization strategies for aliased fields, or to alias a bunch of fields to a single name, so one name could be used to search multiple fields. Solr[1] has a similar functionality.

[1] https://wiki.apache.org/solr/SchemaXml#Copy_Fields

**Comment by phrocker** [comment]
How would this avoid an index scan if you still must expand with the query model and you insert more into the index? This seems that it would net the same lookup if you don't trim the query model.

**Comment by hlgp** [comment]
@drewfarris The current implementation (PR forthcoming) allows for multiple aliases to a single field.
@phrocker It is understood that the model will need to be modified to see any benefit for index scans.
