### ISSUE TITLE
Move Type-related classes into new module as part of microservice refactoring

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#310]
Type- and TypedValue-related classes need to be moved out of **datawave-ws-client** and **datawave-core** into a new module, so that microservice and non-microservice modules can cleanly share those dependencies

**Comment by brianloss** [comment]
I've got a PR coming soon that will move the Normalizers and Type classes.

**Comment by keith-ratcliffe** [comment]
Closed by #311
