### ISSUE TITLE
datawaveWebStart && datawaveWeb failed

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#324]
I am trying to go through the Quickstart install here https://code.nsa.gov/datawave/docs/2.3/getting-started/quickstart-install, but Step 4 fails and therefore I cannot do the guided tour.  **The failing point, that I can identify is this command (see below for details):**  **datawaveWebStart && datawaveWeb**Test

Can anyone help with getting me past this point? Please. Thank you.

Below is the information/results from my attempt:

I have the following running. Base on the Quick-start, this is correct.  I am assuming they all share the same PID, not sure why yet.
 
MacBook-Pro:datawave richard$ allStatus | grep PID
Hadoop is running. PIDs: 40
Accumulo is running. PIDs: 40
DataWave Ingest is running. PIDs: 40
DataWave Web is running. PIDs: 40

However, the EAR deploy failed:
I ran this command as instructed:    
  MacBook-Pro:datawave richard$      datawaveWebStart && datawaveWebTest

result was:

[DW-INFO] - Wildfly is already running
[DW-INFO] - Polling for EAR deployment status every 4 seconds (15 attempts max) 
-bash: /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly/bin/jboss-cli.sh: No such file or directory
    +- Wildfly up (40
 
15296). EAR deployment pending (15/15)
 
**A total of 15/15 attempts failed.**
 
MacBook-Pro:datawave richard$ ls -l /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly
ls: /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly: No such file or directory
 
I would expect the wildfly to be there, but was not.

WILDFLY_HOME value is
/Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly
 
But it does not exist.  In the instructions, it did not say to create this directory manually.
 
MacBook-Pro:datawave richard $ ls -l /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/
-rwxr-xr-x  1 richard  1829750260  1024 Feb  3 00:42 README.md
drwxr-xr-x  7 richard  1829750260   224 Feb  3 00:42 bin
drwxr-xr-x  3 richard  1829750260    96 Feb  3 00:47 data
drwxr-xr-x  9 richard  1829750260   288 Feb  3 00:42 docker

What is odd is the following at the :
 
[DW-INFO] - DataWave build successful
--2019-02-02 23:28:07--  http://download.jboss.org/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
Resolving download.jboss.org (download.jboss.org)... 104.126.128.218
Connecting to download.jboss.org (download.jboss.org)|104.126.128.218|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139025162 (133M) [application/x-gzip]
Saving to: ‘wildfly-10.1.0.Final.tar.gz’
 
wildfly-10.1.0.Final.tar.gz                              100%[=================================================================================================================================>] 132.58M  1.03MB/s    in 2m 23s  
 
2019-02-02 23:30:31 (949 KB/s) - ‘wildfly-10.1.0.Final.tar.gz’ saved [139025162/139025162]
 
I did the allInstall and the result does not seem correct (tones of PID and same PID for all service).

**Comment by keith-ratcliffe** [comment]
Strange. I can't think of anything specifically that would be incompatible with Mac OS, although it's very possible that the quickstart is just not compatible with your OS for some reason. As noted in the System Recommendations, testing has only been performed on Ubuntu and Centos. Any new or recent-ish version of either of those will definitely be compatible.

Others here may have tried this on MacOS and can provide better guidance(?)

**Comment by rqualis-altamiracorp** [comment]
Additional effort made:

I uncompressed the wildfly-10.1.0.Final.tar.gz file and placed it here /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly

I then started started it as a standalone:  ./standalone.sh

Started fine:
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /Users/richard/dev_workspace/datawave/contrib/datawave-quickstart/wildfly

  JAVA: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

13:35:07,178 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
.......
......

13:35:09,116 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0006: Undertow HTTPS listener https listening on 127.0.0.1:8443
13:35:09,197 INFO  [org.jboss.ws.common.management] (MSC service thread 1-1) JBWS022052: Starting JBossWS 5.1.5.Final (Apache CXF 3.1.6) 
13:35:09,294 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
13:35:09,295 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
13:35:09,295 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started in 2384ms - Started 331 of 577 services (393 services are lazy, passive or on-demand)

MacBook-Pro:bin richard$ ./standalone.sh 
=========================================================================

  JBoss Bootstrap Environment

  JBOSS_HOME: /Users/richard.qualis/dev_workspace/datawave/contrib/datawave-quickstart/wildfly

  JAVA: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true

=========================================================================

was able to access the Welcome page:
       http://127.0.0.1:9990/error/index.html

Stopped everything and then execute:  datawaveWebStart && datawaveWebTest

result

[DW-INFO] - Wildfly is already running
[DW-INFO] - Polling for EAR deployment status every 4 seconds (15 attempts max)
    +- Wildfly up (40

80 different PIDs for each, 40 as the first

MacBook-Pro:datawave richard$ allStatus | grep PID
Hadoop is running. PIDs: 40
Accumulo is running. PIDs: 40
DataWave Ingest is running. PIDs: 40
DataWave Web is running. PIDs: 40

Still failed because the EAR was not deployed.  As part of Quickstart Installation, do I have to manually build and deploy the EAR file?  I was doubting that since it was not part of the instructions and quite a bit of lifecycle phases.

**Comment by rqualis-altamiracorp** [comment]
Keith, Sounds like I will have to do a Centos on Docker? If that is the way I have to go, then I will.

**Comment by rqualis-altamiracorp** [comment]
I tried the shell and the result is:

MacBook-Pro:datawave richard$ ashell
-bash: accumulo: command not found

MacBook-Pro:datawave richard$ allInstall
Services are currently running
Hadoop is running. PIDs: 
Accumulo is running. PIDs: 
DataWave Ingest is running. PIDs: 
DataWave Web is running. PIDs: 

The  server log showed nothing was deployed or an attempt was made to deploy to the container.

**Comment by keith-ratcliffe** [comment]
> I tried the shell and the result is:
> 
> MacBook-Pro:datawave richard$ ashell
> -bash: accumulo: command not found
> ...

Hmm. If the `accumulo` command wasn't found (wasn't added to your PATH), then there are larger issues than just the Wildfly deploy. That would indicate that something prevented `bin/env.sh` from sourcing `bin/services/accumulo/bootstrap.sh`, which automatically sets up the Accumulo environment. Likewise for all the other services, I'd imagine. Really hard to say why that'd be.

If possible, I would recommend trying with either Ubuntu or Centos. If you don't have dedicated hardware with one of those, it should also work fine under a VM, given adequate resources are allocated

**Comment by rqualis-altamiracorp** [comment]
Thanks Keith.
I was having some issue with the Docker on the new MacBook Pro, but was able to resolve it.  I am now creating the Docker file to be used on this platform.  I will let you know how it goes.  So far so good.  The only road block that I am working around is I have to be able to ssh to localhosts in Docker.  Working on it

**Comment by rqualis-altamiracorp** [comment]
Created my docker with Centos as OS and tried to run the Quickstart and ran into a build issue, see below.  I also attached the tmp file; changed ext to txt.  I copied information from the trace.  Note, all the artifacts were downloaded:
2019-02-06 13:51:01 (1.35 MB/s) - ‘accumulo-1.9.2-bin.tar.gz’ saved [20877580/20877580]
2019-02-06 13:50:46 (3.30 MB/s) - ‘zookeeper-3.4.5-cdh5.9.1.tar.gz’ saved [29924498/29924498]
etc.....

however, the build failed pointing to a maven argument.  I also tried repelling from Git.  Any suggestions?


[DW-INFO] - Unlinking existing symbolic link: /root/.m2/datawave/properties/dev.properties
[DW-INFO] - Override for dev.properties successful
[DW-INFO] - DataWave build in progress: 'mvn -Pdev -Ddeploy -Dtar -Ddist -Dservices -DskipTests clean install --builder smart -T1.0C'
[DW-INFO] - Build status log: /opt/dev_workspace/datawave/contrib/datawave-quickstart/data/datawave/build-properties/build-progress.tmp
**Unable to parse command line options: Unrecognized option: --builder**

usage: mvn [options] [<goal(s)>] [<phase(s)>]

Options:
 -am,--also-make                        If project list is specified, also
                                        build projects required by the
[build-progress.txt](https://github.com/NationalSecurityAgency/datawave/files/2836589/build-progress.txt)

**Comment by keith-ratcliffe** [comment]
I just pushed a new datawave-quickstart image up to dockerhub for the latest 2.5.0-SNAPSHOT (master), which I created with our [docker-build.sh](https://github.com/NationalSecurityAgency/datawave/blob/master/contrib/datawave-quickstart/docker/docker-build.sh) script.

If you want, you should be able to pull it down via...
```
$ docker pull kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT
```
Also, if you pull the latest master for the datawave repo, you can run the image using our updated [docker-run.sh](https://github.com/NationalSecurityAgency/datawave/blob/master/contrib/datawave-quickstart/docker/docker-run.sh) script. E.g., ....
```
$ ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -it
```
