### ISSUE TITLE
allInstall process freeze - help please

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#328]
I was able to build the data wave without any errors, however after allInstall, in stopped at the following (I added more detail below the 5 to 6 lines) - any suggestions:

environment:user.dir=/opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/datawave/datawave-ingest-install/bin/ingest
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.accumulo.fate.zookeeper.ZooSession$ZooWatcher@6622fc65
19/02/08 22:34:52 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/02/08 22:34:52 INFO zookeeper.ClientCnxn: Socket connection established, initiating session, client: /127.0.0.1:34628, server: localhost/127.0.0.1:2181
19/02/08 22:34:53 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x168cf38e18e0008, negotiated timeout = 30000
19/02/08 22:34:53 WARN impl.ServerClient: There are no tablet servers: check that zookeeper and accumulo are running.

BELOW IS MORE DETAILS - MOSTLY THOSE AROUND THE ERROR POINTS:

19/02/08 22:23:36 INFO namenode.NNStorageRetentionManager: Going to retain 1 images with txid >= 0
19/02/08 22:23:36 INFO util.ExitUtil: Exiting with status 0
19/02/08 22:23:36 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at 7d7bc35980f4/172.17.0.2
************************************************************/

[DW-INFO] - Hadoop initialized and ready to start...

      Start command: hadoopStart
       Stop command: hadoopStop
     Status command: hadoopStatus

[DW-INFO] - See $DW_CLOUD_HOME/bin/services/hadoop/bootstrap.sh to view/edit commands as needed

[DW-INFO] - Accumulo and ZooKeeper tarballs extracted and symlinked
[DW-INFO] - Accumulo accumulo-site.xml written
[DW-INFO] - Accumulo client.conf written
[DW-INFO] - Created directory: /opt/dev_workspace/datawave/contrib/datawave-quickstart/data/heapdumps
[DW-INFO] - Starting Hadoop, so that we can initialize Accumulo
This script is Deprecated. Instead use start-dfs.sh and start-yarn.sh
19/02/08 22:24:13 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Starting namenodes on [localhost]
The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:y6fL+KhI1KaWCXDt1aAjwwjp7AUm0Gq88errQInjOQY.
ECDSA key fingerprint is MD5:17:65:0c:ad:19:c1:01:fe:ea:1e:eb:92:58:ea:b9:4b.
Are you sure you want to continue connecting (yes/no)? yes
localhost: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
localhost: starting namenode, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/hadoop/hadoop-install/logs/hadoop-root-namenode-7d7bc35980f4.out
localhost: starting datanode, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/hadoop/hadoop-install/logs/hadoop-root-datanode-7d7bc35980f4.out
Starting secondary namenodes [0.0.0.0]
The authenticity of host '0.0.0.0 (0.0.0.0)' can't be established.
ECDSA key fingerprint is SHA256:y6fL+KhI1KaWCXDt1aAjwwjp7AUm0Gq88errQInjOQY.
ECDSA key fingerprint is MD5:17:65:0c:ad:19:c1:01:fe:ea:1e:eb:92:58:ea:b9:4b.
Are you sure you want to continue connecting (yes/no)? yes
0.0.0.0: Warning: Permanently added '0.0.0.0' (ECDSA) to the list of known hosts.
0.0.0.0: starting secondarynamenode, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/hadoop/hadoop-install/logs/hadoop-root-secondarynamenode-7d7bc35980f4.out
19/02/08 22:26:14 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
starting yarn daemons
starting resourcemanager, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/hadoop/logs/yarn--resourcemanager-7d7bc35980f4.out
localhost: starting nodemanager, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/hadoop/hadoop-install/logs/yarn-root-nodemanager-7d7bc35980f4.out
chown: missing operand after ‘/opt/dev_workspace/datawave/contrib/datawave-quickstart/hadoop/logs’
Try 'chown --help' for more information.
starting historyserver, logging to /opt/dev_workspace/datawave/contrib/datawave-quickstart/hadoop/logs/mapred--historyserver-7d7bc35980f4.out

....

[DW-INFO] - For detailed status visit 'http://localhost:50070/dfshealth.html#tab-overview' in your browser
19/02/08 22:26:26 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Safe mode is OFF
[DW-INFO] - Starting ZooKeeper, so that we can initialize Accumulo
JMX enabled by default
Using config: /opt/dev_workspace/datawave/contrib/datawave-quickstart/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED
19/02/08 22:26:35 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-02-08 22:26:40,137 [conf.ConfigSanityCheck] WARN : Use of instance.dfs.uri and instance.dfs.dir are deprecated. Consider using instance.volumes instead.
2019-02-08 22:26:40,524 [util.NativeCodeLoader] WARN : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-02-08 22:26:41,824 [init.Initialize] INFO : Hadoop Filesystem is hdfs://localhost:9000
2019-02-08 22:26:41,824 [init.Initialize] INFO : Accumulo data dirs are [hdfs://localhost:9000/accumulo]
2019-02-08 22:26:41,824 [init.Initialize] INFO : Zookeeper server is localhost:2181
2019-02-08 22:26:41,824 [init.Initialize] INFO : Checking if Zookeeper is available. If this hangs, then you need to make sure zookeeper is running
2019-02-08 22:26:42,741 [Configuration.deprecation] INFO : dfs.replication.min is deprecated. Instead, use dfs.namenode.replication.min
2019-02-08 22:26:43,138 [Configuration.deprecation] INFO : dfs.block.size is deprecated. Instead, use dfs.blocksize
2019-02-08 22:26:44,368 [conf.AccumuloConfiguration] INFO : Loaded class : org.apache.accumulo.server.security.handler.ZKAuthorizor
2019-02-08 22:26:44,372 [conf.AccumuloConfiguration] INFO : Loaded class : org.apache.accumulo.server.security.handler.ZKAuthenticator
2019-02-08 22:26:44,377 [conf.AccumuloConfiguration] INFO : Loaded class : org.apache.accumulo.server.security.handler.ZKPermHandler

[DW-INFO] - Accumulo initialized and ready to start...

      Start command: accumuloStart
       Stop command: accumuloStop
     Status command: accumuloStatus

[DW-INFO] - See $DW_CLOUD_HOME/bin/services/accumulo/bootstrap.sh to view/edit commands as needed

[DW-INFO] - DataWave Ingest tarball extracted and symlinked
19/02/08 22:27:01 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/08 22:27:06 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/08 22:27:13 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[DW-INFO] - Stopping Accumulo to update classpath, etc...
Accumulo is already stopped
JMX enabled by default
Using config: /opt/dev_workspace/datawave/contrib/datawave-quickstart/zookeeper/bin/../conf/zoo.cfg
Stopping zookeeper ... STOPPED
[DW-INFO] - Removing any existing jars from /opt/dev_workspace/datawave/contrib/datawave-quickstart/accumulo/lib/ext
[DW-INFO] - Copying DataWave jars into /opt/dev_workspace/datawave/contrib/datawave-quickstart/accumulo/lib/ext
[DW-INFO] - Starting Accumulo, so that we can initialize DataWave Ingest
JMX enabled by default
Using config: /opt/dev_workspace/datawave/contrib/datawave-quickstart/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED

....

Starting monitor on localhost
Starting tablet servers .... done
Starting tserver on localhost
2019-02-08 22:27:23,829 [conf.ConfigSanityCheck] WARN : Use of instance.dfs.uri and instance.dfs.dir are deprecated. Consider using instance.volumes instead.
2019-02-08 22:27:25,508 [util.NativeCodeLoader] WARN : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-02-08 22:27:29,020 [server.Accumulo] INFO : Attempting to talk to zookeeper
2019-02-08 22:27:29,483 [server.Accumulo] INFO : ZooKeeper connected and initialized, attempting to talk to HDFS
2019-02-08 22:27:30,111 [server.Accumulo] INFO : Connected to HDFS
Starting master on localhost
Starting gc on localhost
Starting tracer on localhost

[DW-INFO] - For detailed status visit 'http://localhost:9995' in your browser
[DW-INFO] - Executing the following Accumulo shell script: /tmp/install-ingest.sh-accumulo-shell.TcySN
[DW-INFO] - /tmp/install-ingest.sh-accumulo-shell.TcySN contents... 

createnamespace datawave
config -s table.classpath.context=datawave
createtable datawave.queryMetrics_m
setauths -s PUBLIC,PRIVATE,FOO,BAR,DEF
quit

2019-02-08 22:27:51,446 [client.ClientConfiguration] INFO : Loaded client configuration file /opt/dev_workspace/datawave/contrib/datawave-quickstart/accumulo/conf/client.conf
2019-02-08 22:27:52,026 [client.Cli

.....

pedia
For decreased latency, one can add the -mapOnly flag at the cost of possibly overcounting duplicate records
Running main
log4j:ERROR No output stream or file set for the appender named [null].
19/02/08 22:34:51 INFO datawave.ingest: InputPaths is /Ingest/wikipedia/enwiki-20130305-pages-articles-brief.xml
19/02/08 22:34:51 INFO datawave.ingest: Adding resource all-config.xml

....

9/02/08 22:34:52 INFO datawave.ingest: Setting mapred.map.child.java.opts = "-Xmx1024m -XX:+UseConcMarkSweepGC -Dfile.encoding=UTF8 -Duser.timezone=GMT -XX:+UseNUMA "
19/02/08 22:34:52 INFO datawave.ingest: Setting mapred.reduce.child.java.opts = "-Xmx1024m -XX:+UseConcMarkSweepGC -Dfile.encoding=UTF8 -Duser.timezone=GMT -XX:+UseNUMA "
19/02/08 22:34:52 INFO datawave.ingest: Setting AccumuloOutputFormat.WriteOpts.BatchWriterConfig = "    11#maxMemory=100000000,maxWriteThreads=8"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.task.io.sort.mb = "768"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.task.io.sort.factor = "100"
19/02/08 22:34:52 INFO datawave.ingest: Setting bulk.ingest.mapper.threads = "0"
19/02/08 22:34:52 INFO datawave.ingest: Setting bulk.ingest.mapper.workqueue.size = "10000"
19/02/08 22:34:52 INFO datawave.ingest: Setting io.file.buffer.size = "1048576"
19/02/08 22:34:52 INFO datawave.ingest: Setting dfs.bytes-per-checksum = "4096"
19/02/08 22:34:52 INFO datawave.ingest: Setting io.sort.record.percent = ".10"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.map.sort.spill.percent = ".50"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.map.output.compress = "true"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.map.output.compress.codec = "org.apache.hadoop.io.compress.DefaultCodec"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.output.fileoutputformat.compress.type = "RECORD"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.task.timeout = "600000"
19/02/08 22:34:52 INFO datawave.ingest: Setting context.writer.max.cache.size = "2500"
19/02/08 22:34:52 INFO datawave.ingest: Setting mapreduce.job.queuename = "liveIngestQueue"
19/02/08 22:34:52 INFO datawave.ingest: Setting data.name.override = "wikipedia"
19/02/08 22:34:52 INFO datawave.ingest: Replacing ${DATAWAVE_INGEST_HOME} with /opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/datawave/datawave-ingest-install/bin/ingest/../..
19/02/08 22:34:52 INFO datawave.ingest: Setting MONITOR_SERVER_HOST to localhost
19/02/08 22:34:52 DEBUG data.TypeRegistry: No helper class defined for type: all
19/02/08 22:34:52 DEBUG data.TypeRegistry: No reader class defined for type: all
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: all
19/02/08 22:34:52 DEBUG data.TypeRegistry: Registered type <type><typeName>all</typeName></type>
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: mycsv
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: mycsv
19/02/08 22:34:52 DEBUG data.TypeRegistry: Registered type <type><typeName>mycsv</typeName><outputName>csv</outputName></type>
19/02/08 22:34:52 DEBUG data.TypeRegistry: No helper class defined for type: file-level
19/02/08 22:34:52 DEBUG data.TypeRegistry: No reader class defined for type: file-level
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: file-level
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: file-level
19/02/08 22:34:52 DEBUG data.TypeRegistry: No helper class defined for type: metrics-summary
19/02/08 22:34:52 DEBUG data.TypeRegistry: No reader class defined for type: metrics-summary
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: metrics-summary
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: metrics-summary
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: wikipedia
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: wikipedia
19/02/08 22:34:52 DEBUG data.TypeRegistry: Registered type <type><typeName>wikipedia</typeName></type>
19/02/08 22:34:52 DEBUG data.TypeRegistry: No reader class defined for type: error
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: error
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: error
19/02/08 22:34:52 DEBUG data.TypeRegistry: Registered type <type><typeName>error</typeName></type>
19/02/08 22:34:52 DEBUG data.TypeRegistry: No handler classes defined for type: myjson
19/02/08 22:34:52 DEBUG data.TypeRegistry: No filter classes defined for type: myjson
19/02/08 22:34:52 DEBUG data.TypeRegistry: Registered type <type><typeName>myjson</typeName><outputName>tvmaze</outputName></type>
19/02/08 22:34:52 ERROR datawave.ingest: Configuration: core-default.xml, core-site.xml, all-config.xml, dateindex-ingest-config.xml, edge-ingest-config.xml, error-ingest-config.xml, ingest-config.xml, metadata-config.xml, mycsv-ingest-config.xml, myjson-ingest-config.xml, nyctlc-ingest-config.xml, shard-ingest-config.xml, wikipedia-ingest-config.xml
19/02/08 22:34:52 ERROR datawave.ingest: getStrings('ingest.data.types') = ,wikipedia,mycsv,myjson,,
19/02/08 22:34:52 ERROR datawave.ingest: getStrings('data.name') = wikipedia
19/02/08 22:34:52 ERROR datawave.ingest: name[0] = 'all'
19/02/08 22:34:52 ERROR datawave.ingest: name[1] = 'mycsv'
19/02/08 22:34:52 ERROR datawave.ingest: name[2] = 'wikipedia'
19/02/08 22:34:52 ERROR datawave.ingest: name[3] = 'error'
19/02/08 22:34:52 ERROR datawave.ingest: name[4] = 'myjson'
19/02/08 22:34:52 INFO client.ClientConfiguration: Loaded client configuration file /opt/dev_workspace/datawave/contrib/datawave-quickstart/accumulo/conf/client.conf
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-cdh5.9.1--1, built on 01/11/2017 21:46 GMT
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:host.name=7d7bc35980f4
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.version=1.8.0_201
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.home=/opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/java/jdk-8-linux-x64/jre
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.class.path=../../co

.......

19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/opt/dev_workspace/datawave/contrib/datawave-quickstart/hadoop/lib/native
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:os.version=4.9.125-linuxkit
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:user.name=root
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:user.home=/root
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Client environment:user.dir=/opt/dev_workspace/datawave/contrib/datawave-quickstart/bin/services/datawave/datawave-ingest-install/bin/ingest
19/02/08 22:34:52 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.accumulo.fate.zookeeper.ZooSession$ZooWatcher@6622fc65
19/02/08 22:34:52 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/02/08 22:34:52 INFO zookeeper.ClientCnxn: Socket connection established, initiating session, client: /127.0.0.1:34628, server: localhost/127.0.0.1:2181
19/02/08 22:34:53 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x168cf38e18e0008, negotiated timeout = 30000
19/02/08 22:34:53 WARN impl.ServerClient: There are no tablet servers: check that zookeeper and accumulo are running.

**Comment by keith-ratcliffe** [comment]
>19/02/08 22:34:53 WARN impl.ServerClient: There are no tablet servers: check that zookeeper and accumulo are running.

Accumulo tserver died on you for some reason. What do the tserver logs have to say?
```
ls -al /opt/dev_workspace/datawave/contrib/datawave-quickstart/accumulo/logs/tserver*
```

**Comment by keith-ratcliffe** [comment]
Doesn't look like password-less SSH was established
Also, what's the execution environment, in terms of OS and host? Linux on VM? Docker?

**Comment by rqualis-altamiracorp** [comment]
Keith,

I attached both log files.  I am seeing some timeouts:

2019-02-08 22:27:31,947 [server.Accumulo] INFO : instance.zookeeper.timeout = 30s

Also, I am using a image created with Docker and the OS ic cents7


[tracer_7d7bc35980f4.debug.log](https://github.com/NationalSecurityAgency/datawave/files/2847250/tracer_7d7bc35980f4.debug.log)
[tserver_7d7bc35980f4.log](https://github.com/NationalSecurityAgency/datawave/files/2847251/tserver_7d7bc35980f4.log)

**Comment by keith-ratcliffe** [comment]
Should be some *.err and *.out files there too. Do they have anything in them?

**Comment by rqualis-altamiracorp** [comment]
All  err are empty.  However, I noticed some time sensitive information that could result in timeout...not sure if it is related.

Note the stack of errors in monitor_7d7bc35980f4.debug.log. I am not sure if this is related
[monitor_7d7bc35980f4.debug.log](https://github.com/NationalSecurityAgency/datawave/files/2847283/monitor_7d7bc35980f4.debug.log)
[master_7d7bc35980f4.debug.log](https://github.com/NationalSecurityAgency/datawave/files/2847284/master_7d7bc35980f4.debug.log)
[master_7d7bc35980f4.log](https://github.com/NationalSecurityAgency/datawave/files/2847285/master_7d7bc35980f4.log)
[gc_7d7bc35980f4.debug.log](https://github.com/NationalSecurityAgency/datawave/files/2847286/gc_7d7bc35980f4.debug.log)






[tracer_7d7bc35980f4.debug.log](https://github.com/NationalSecurityAgency/datawave/files/2847278/tracer_7d7bc35980f4.debug.log)
[tracer_7d7bc35980f4.log](https://github.com/NationalSecurityAgency/datawave/files/2847279/tracer_7d7bc35980f4.log)

**Comment by rqualis-altamiracorp** [comment]
Keith, also, when I login into the container, I can ssh localhost with no password.

**Comment by rqualis-altamiracorp** [comment]
eventually, this showed up:

19/02/09 00:27:55 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x168cf38e18e0008, likely server has closed socket, closing socket connection and attempting reconnect
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Socket connection established, initiating session, client: /127.0.0.1:34994, server: localhost/127.0.0.1:2181
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Unable to reconnect to ZooKeeper service, session 0x168cf38e18e0008 has expired, closing socket connection
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: EventThread shut down
19/02/09 00:27:57 WARN zookeeper.ZooCache: Saw (possibly) transient exception communicating with ZooKeeper, will retry
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /accumulo/cfed23d5-033f-4dac-b8d9-3ac12950d26f
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:127)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
	at org.apache.accumulo.fate.zookeeper.ZooCache$2.run(ZooCache.java:394)
	at org.apache.accumulo.fate.zookeeper.ZooCache$2.run(ZooCache.java:366)
	at org.apache.accumulo.fate.zookeeper.ZooCache$ZooRunnable.retry(ZooCache.java:260)
	at org.apache.accumulo.fate.zookeeper.ZooCache.get(ZooCache.java:423)
	at org.apache.accumulo.fate.zookeeper.ZooCache.get(ZooCache.java:352)
	at org.apache.accumulo.core.client.ZooKeeperInstance.getInstanceID(ZooKeeperInstance.java:207)
	at org.apache.accumulo.core.zookeeper.ZooUtil.getRoot(ZooUtil.java:40)
	at org.apache.accumulo.core.client.impl.ServerClient.getConnection(ServerClient.java:137)
	at org.apache.accumulo.core.client.impl.ServerClient.getConnection(ServerClient.java:124)
	at org.apache.accumulo.core.client.impl.ServerClient.getConnection(ServerClient.java:119)
	at org.apache.accumulo.core.client.impl.ServerClient.executeRaw(ServerClient.java:100)
	at org.apache.accumulo.core.client.impl.ServerClient.execute(ServerClient.java:64)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.<init>(ConnectorImpl.java:73)
	at org.apache.accumulo.core.client.ZooKeeperInstance.getConnector(ZooKeeperInstance.java:308)
	at datawave.ingest.data.config.ingest.AccumuloHelper.getConnector(AccumuloHelper.java:94)
	at datawave.ingest.mapreduce.job.IngestJob.configureTables(IngestJob.java:740)
	at datawave.ingest.mapreduce.job.IngestJob.run(IngestJob.java:297)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at datawave.ingest.mapreduce.job.IngestJob.main(IngestJob.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
19/02/09 00:27:57 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.accumulo.fate.zookeeper.ZooSession$ZooWatcher@5553d0f5
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Socket connection established, initiating session, client: /127.0.0.1:34998, server: localhost/127.0.0.1:2181
19/02/09 00:27:57 INFO zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x168cf38e18e000a, negotiated timeout = 30000

**Comment by keith-ratcliffe** [comment]
I'm guessing this a Docker image that you built using your own custom Dockerfile?

**Comment by rqualis-altamiracorp** [comment]
Yes.  I have attached the file

[Dockerfile_datawave.txt](https://github.com/NationalSecurityAgency/datawave/files/2847364/Dockerfile_datawave.txt)

**Comment by rqualis-altamiracorp** [comment]
I did a control-c and then it shows accumulo running

[root@7d7bc35980f4 datawave]# allInstall
Services are currently running
Hadoop is running. PIDs: 5534 5617 5811 5968 6048 6101
Accumulo is running. PIDs:  6981
DataWave Ingest is not running
DataWave Web is not running

**Comment by rqualis-altamiracorp** [comment]
I did a control-c, then ssh to 127.0.0.1 and entered yes, the exit then verified no password on this and then re-tried (note, I had done ssh localhost before). Not sure why DataWave Web won't start

[root@7d7bc35980f4 datawave]# allStatus
Hadoop is running. PIDs: 17275 17365 17563 17728 17814 17873
Accumulo is running. PIDs: 18549 18689 18797 18886 18327
DataWave Ingest is not running
DataWave Web is not running

**Comment by keith-ratcliffe** [comment]
You've done very well to get this far. Creating a docker image that runs the entire stack is non-trivial.

There are many variables to account for, and unfortunately I just don't think we can assist much more with troubleshooting this particular scenario. 

We can really only support two use cases, and both begin with starting from either Ubuntu or Centos as the host OS, which we've tested. Those are...

- Use either Ubuntu or Centos to perform the local install as documented on our project site, or...

- Use either Ubuntu or Centos to build a Docker image with our docker-build.sh script, as referenced on the other ticket.

Alternatively, you could `docker pull ...` the existing image that I referenced in the other ticket as well

**Comment by rqualis-altamiracorp** [comment]
Thanks Keith. 
I will pull the one you created and go forward with that.

In parallel, as time permit, I will surely try to get the one I started working.  There are some benefits to it, I think.  I will surely share it once done.

Thanks for all the help tho....

**Comment by keith-ratcliffe** [comment]
No problem. Good luck. FWIW, one of the key tricks used by the docker-build.sh script is that it uses your local host/os to perform the DW build, entirely outside the Docker image build. That way, you avoid writing all the ~/.m2/repository jars to the image itself. That decreases the final image size by at least 1 metric ton of gigabytes. The other trick is that it just passes your local datawave.git root dir as the image context, and makes strategic use of the .dockerignore file to ensure that any built/downloaded tarballs get passed thru into the image. Those optimizations required at least 1 metric ton of trial/error :)

**Comment by rqualis-altamiracorp** [comment]
Thanks Keith.  I am going with the quickest option at this point due to time constraints.  I just pulled the existing image.  What is the docker command with params to build the container from that image? please/thanks

**Comment by keith-ratcliffe** [comment]
@rqualis-altamiracorp , once you've pulled the image, you can just use the [docker-run.sh](https://github.com/NationalSecurityAgency/datawave/blob/master/contrib/datawave-quickstart/docker/docker-run.sh) script to use it, follow along with the tour, etc

**Comment by rqualis-altamiracorp** [comment]
Keith,
I am trying your scripts and here is what I am finding

1.  This run option run fine: ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -it
[root@9df13ff32485 datawave-quickstart]# allStatus
Hadoop is running. PIDs: 335 524 757 913 1075 1295
Accumulo is running. PIDs: 2173 1571
DataWave Ingest is not running
DataWave Web is not running

and I am able to get to http://localhost:50070/dfshealth.html#tab-overview

2.  Because I wanted DataWave Ingest and DataWave Web running (atleast the later), kill the above, restarted comp just to make sure, and then ran ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -d datawave-bootstrap.sh --ingest --web.  The results were :

MacBook-Pro:docker richard.qualis$ ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -d datawave-bootstrap.sh --ingest --web
6db8130bd08168efe46cb52a8232961b0007038655396b05379f4796246004c3
MacBook-Pro:docker richard.qualis$ 

MacBook-Pro:docker richard.qualis$ docker container ls
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                                                                                                    NAMES
6db8130bd081        kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT   "docker-entrypoint.s…"   51 seconds ago      Up 48 seconds       2181/tcp, 8088/tcp, 0.0.0.0:8443->8443/tcp, 0.0.0.0:9995->9995/tcp, 9000/tcp, 0.0.0.0:50070->50070/tcp   gracious_germain

Issues:
1. MacBook-Pro:docker richard.qualis$ allStatus
-bash: allStatus: command not found

pretty much I cannot get to do the TourGuide. Help please

**Comment by rqualis-altamiracorp** [comment]
I got around it or maybe was doing it incorrect.  I did the following:
docker exec -t -i ${CONTAINER ID} /bin/bash and once in all was ok
