### ISSUE TITLE
Build the DATAWAVE microservices failed - followed instructions in README

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#330]
Following the instructions in the datawave-master/services/README.md file (# Getting Started section) and got the error below:

Steps followed:

cd /path/to/datawave/services/build-parent
mvn -Pexec clean install -DskipTests -Pdocker 

Not expecting I would have to change the pom file

[INFO] Reactor Summary:
[INFO] 
[INFO] DataWave Microservices Parent 1.4-SNAPSHOT ......... SUCCESS [  1.259 s]
[INFO] DataWave Microservices Spring Boot Service Parent 1.3-SNAPSHOT SUCCESS [  0.188 s]
[INFO] common-utils 1.1-SNAPSHOT .......................... SUCCESS [  2.198 s]
[INFO] accumulo-utils 1.3-SNAPSHOT ........................ SUCCESS [  1.332 s]
[INFO] base-rest-responses 1.1-SNAPSHOT ................... SUCCESS [  1.080 s]
[INFO] type-utils 1.1-SNAPSHOT ............................ SUCCESS [  1.413 s]
[INFO] metadata-utils 1.1-SNAPSHOT ........................ SUCCESS [  1.255 s]
[INFO] metrics-reporter 1.3-SNAPSHOT ...................... SUCCESS [  0.355 s]
[INFO] authorization-api 1.4-SNAPSHOT ..................... SUCCESS [  0.399 s]
[INFO] audit-api 1.5-SNAPSHOT ............................. SUCCESS [  0.422 s]
[INFO] hazelcast-common 1.4-SNAPSHOT ...................... SUCCESS [  0.812 s]
[INFO] hazelcast-client 1.4-SNAPSHOT ...................... SUCCESS [  0.543 s]
[INFO] spring-boot-starter-datawave 1.3-SNAPSHOT .......... SUCCESS [  1.837 s]
[INFO] config-service 1.3-SNAPSHOT ........................ **FAILURE** [  0.244 s]
[INFO] hazelcast-service 1.4-SNAPSHOT ..................... SKIPPED
[INFO] authorization-service 1.4-SNAPSHOT ................. SKIPPED
[INFO] audit-service 1.7-SNAPSHOT ......................... SKIPPED
[INFO] DataWave Microservices Build Parent 1.2-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] **BUILD FAILURE**
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.863 s
[INFO] Finished at: 2019-02-11T10:51:59-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.4:revision (default) on project config-service: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by keith-ratcliffe** [comment]
Cannot replicate on latest master. If possible, please reply with your output from...
```
git log --oneline | head -n 5
```
Note: The build assumes that source code resides in a local git repo. If that is not the case, then your options are, **(1)** change the POM, **(2)** build from the original clone of **datawave.git**, or **(3)** `git init` and `git add` the source code for a new git repo.

Building from the original clone of **datawave.git** is preferred and also the only use case that we can support

**Comment by rqualis-altamiracorp** [comment]
If I run that command **inside the container**, that is after running the following:

$ docker pull kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT
$ ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -it

I get the following:
 
[root@6db8130bd081 datawave]# git log --oneline | head -n 5
04712c1 Source Branch :: master :: Source Commit :: b5ba803cdc584e200f9c53b46740b8cfb381eb3e

**If run out side of the container: that is on my local workstation**

fatal: not a git repository (or any of the parent directories): .git

To stay inline with what you support, I will build from the original clone of **datawave.git**, but what does that mean keeping in mind that I am using the: 
$ docker pull kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT
$ ./docker-run.sh kratcliffe/datawave-quickstart:2.5.0-SNAPSHOT -it
?

Thanks

**Comment by rqualis-altamiracorp** [comment]
Note, I do have the .git

drwxrwxrwx  14 richard.qualis  1829750260    448 Feb  8 21:00 .git
inside of  .... dev_workspace/datawave

**Comment by keith-ratcliffe** [comment]
Not sure I understand. If the following...

```
$ cd dev_workspace/datawave
$ git log --oneline | head -n 5 
```
...results in the error...

> fatal: not a git repository (or any of the parent directories): .git

...then that means the **.git** directory has probably become corrupted, in which case you should probably delete your `dev_workspace/datawave` dir and re-clone the remote repo into a new directory

The only other explanation for that error that I can think of is that you were not inside `dev_workspace/datawave` when you ran the `git log` command.

But I'm assuming that from your original issue (i.e., the Maven build failure), that the problem is the former....has become corrupted

**Comment by rqualis-altamiracorp** [comment]
Keith,
cd /opt/datawave
**produces**
[root@6db8130bd081 datawave]# git log --oneline | head -n 5
`04712c1 Source Branch :: master :: Source Commit :: b5ba803cdc584e200f9c53b46740b8cfb381eb3e`

I also tried the following:

cd /opt/datawave
mvn -Pexec clean install -DskipTests -Pdocker

then 

cd /opt/datawave/services/build-parent
mvn -Pexec clean install -DskipTests -Pdocker

And got

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DataWave Microservices Parent 1.4-SNAPSHOT ......... SUCCESS [  9.171 s]
[INFO] DataWave Microservices Spring Boot Service Parent 1.3-SNAPSHOT SUCCESS [  1.273 s]
[INFO] common-utils 1.1-SNAPSHOT .......................... SUCCESS [  6.186 s]
[INFO] accumulo-utils 1.3-SNAPSHOT ........................ SUCCESS [  8.013 s]
[INFO] base-rest-responses 1.1-SNAPSHOT ................... SUCCESS [  5.224 s]
[INFO] type-utils 1.1-SNAPSHOT ............................ SUCCESS [  3.660 s]
[INFO] metadata-utils 1.1-SNAPSHOT ........................ SUCCESS [  4.496 s]
[INFO] metrics-reporter 1.3-SNAPSHOT ...................... SUCCESS [  0.962 s]
[INFO] authorization-api 1.4-SNAPSHOT ..................... SUCCESS [  0.965 s]
[INFO] audit-api 1.5-SNAPSHOT ............................. SUCCESS [  2.500 s]
[INFO] hazelcast-common 1.4-SNAPSHOT ...................... SUCCESS [  4.764 s]
[INFO] hazelcast-client 1.4-SNAPSHOT ...................... SUCCESS [  3.234 s]
[INFO] spring-boot-starter-datawave 1.3-SNAPSHOT .......... SUCCESS [ 16.103 s]
[INFO] config-service 1.3-SNAPSHOT ........................ FAILURE [ 27.097 s]
[INFO] hazelcast-service 1.4-SNAPSHOT ..................... SKIPPED
[INFO] authorization-service 1.4-SNAPSHOT ................. SKIPPED
[INFO] audit-service 1.7-SNAPSHOT ......................... SKIPPED
[INFO] DataWave Microservices Build Parent 1.2-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:37 min
[INFO] Finished at: 2019-02-11T20:42:40Z
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.1.1:build (tag-image) on project config-service: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :config-service

**Comment by keith-ratcliffe** [comment]
As for our quickstart docker image, rather than include the entire remote **datawave.git** repo and its entire commit history, our **docker-build.sh** script simply `git init`'s a new repo inside the image and just references the source branch name and source commit id in the given commit message....

> Source Branch :: master :: Source Commit :: `b5ba803cdc584e200f9c53b46740b8cfb381eb3e`

So, the expectation for builds here is that you'd only use the docker image to make some minor changes, test those changes, and generate a patch file if needed, not that you'd use it for your primary development environment. So, the commit message here allows you to know which commit and which branch you'd need to apply your patch to, i.e., on an actual **datawave.git** clone

Also, as for the services/build-parent Maven build, it wouldn't really make sense to activate the `docker` profile (`-Pdocker`) when building inside the running docker container

**Comment by keith-ratcliffe** [comment]
In other words, `mvn -Pexec clean install -DskipTests -Pdocker` from within the running container is essentially trying to create new docker images (one for each microservice) from inside the container itself. You only need the `docker` profile activated if you intend to run/deploy the microservices as Docker containers. That's not really required for development and testing. For that, it's probably easiest just run each microservice via `java -jar ...` as described in services/README

**Comment by rqualis-altamiracorp** [comment]
My first option was to try the steps outside of the container and it still failed with the same error.

I following the following steps from the file, but this mvn -Pexec clean install failed.  As expected, the java -jar ... would fail, but I still tried and sure enough it failed.

I am going to delete the docker-master, pull it again, and try from start.


# Getting Started

The quickest way to get stared is as follows. First, copy the `.example` files
in the `sample_configuration` directory to the same name without `.example`
(e.g., `authorization-dev.yml.example` becomes `authorization-dev.yml`). Edit
the files you copied and customize any properties you wish.

```bash
cd sample_configuration
for f in *.yml.example; do
    cp ${f} ${f%.example}
done
```

Next, build the DATAWAVE microservices.

```bash
cd /path/to/datawave/services/build-parent
mvn -Pexec clean install
# You can add -DskipTests to skip running unit tests
# You can add -Pdocker to build Docker images
```

Now launch the configuration service. Specify the `sample_configuration` for the
configuration repository.

```bash
cd /path/to/datawave/services
java -jar config-service/target/config-service*-exec.jar --spring.profiles.active=dev,nomessaging,native,open_actuator --spring.cloud.config.server.native.searchLocations=file://$PWD/sample_configuration 
```

**Comment by rqualis-altamiracorp** [comment]
Still failed:

No container being used:

1. Pulled from repos a new snap fo the code and put in /Users/richard.qualis/dev_workspace/datawave-master/services/build-parent

2. Followed the exact steps under "Getting Started" in the README.md file.

Results were the same:


[INFO] Reactor Summary:
[INFO] 
[INFO] DataWave Microservices Parent 1.4-SNAPSHOT ......... SUCCESS [  1.188 s]
[INFO] DataWave Microservices Spring Boot Service Parent 1.3-SNAPSHOT SUCCESS [  0.131 s]
[INFO] common-utils 1.1-SNAPSHOT .......................... SUCCESS [  2.173 s]
[INFO] accumulo-utils 1.3-SNAPSHOT ........................ SUCCESS [  1.214 s]
[INFO] base-rest-responses 1.1-SNAPSHOT ................... SUCCESS [  0.993 s]
[INFO] type-utils 1.1-SNAPSHOT ............................ SUCCESS [  1.275 s]
[INFO] metadata-utils 1.1-SNAPSHOT ........................ SUCCESS [  1.066 s]
[INFO] metrics-reporter 1.3-SNAPSHOT ...................... SUCCESS [  0.306 s]
[INFO] authorization-api 1.4-SNAPSHOT ..................... SUCCESS [  0.362 s]
[INFO] audit-api 1.5-SNAPSHOT ............................. SUCCESS [  0.341 s]
[INFO] hazelcast-common 1.4-SNAPSHOT ...................... SUCCESS [  0.709 s]
[INFO] hazelcast-client 1.4-SNAPSHOT ...................... SUCCESS [  0.454 s]
[INFO] spring-boot-starter-datawave 1.3-SNAPSHOT .......... SUCCESS [  1.470 s]
[INFO] config-service 1.3-SNAPSHOT ........................ FAILURE [  0.155 s]
[INFO] hazelcast-service 1.4-SNAPSHOT ..................... SKIPPED
[INFO] authorization-service 1.4-SNAPSHOT ................. SKIPPED
[INFO] audit-service 1.7-SNAPSHOT ......................... SKIPPED
[INFO] DataWave Microservices Build Parent 1.2-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.344 s
[INFO] Finished at: 2019-02-11T16:28:38-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.4:revision (default) on project config-service: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :config-service

**Comment by keith-ratcliffe** [comment]
> 1. Pulled from repos a new snap fo the code and put in /Users/richard.qualis/dev_workspace/datawave-master/services/build-parent

Please share the exact steps you performed to do this

**Comment by rqualis-altamiracorp** [comment]
1. Went to https://github.com/NationalSecurityAgency/datawave/
2. Clicked on Clone with HTTPS Use Git or checkout with SVN using the web URL..... and downloaded the zip file
3. Copied the directory into my location:
cp -R 1. /Download/datawave-master    /Users/richard.qualis/dev_workspace/

**Comment by keith-ratcliffe** [comment]
Downloading the zip archive is _not_ the same as cloning the repository. You need to execute a `git clone` command for that

**Comment by rqualis-altamiracorp** [comment]
I know, but the site indicated I could do either and then proceed.,

I will do a clone using the GIt and see if the results are different

**Comment by rqualis-altamiracorp** [comment]
It worked. Sorry for being such a thorn in the side.  I thought it didn't matter zip or clone.  

Suggestion though, make a note of that in the README file that must be a clone
