### ISSUE TITLE
In Quickstart, 5 Datawave Menu Options Are Forbidden

### ISSUE THREAD

**Issue by medined** [NationalSecurityAgency/datawave#35]
I performed the following steps:
* forked, then cloned the Datawave project.
* updated docker to use devicemapper as the storage driver.
* enabled docker's experimental mode.
* ran docker-build.sh which created the 'datawave-quickstart' image.
* ran './docker-run-example.sh 1.0.0-SNAPSHOT -it'.
* visited 
  * https://localhost:8443/DataWave/DataDictionary
  * https://localhost:8443/DataWave/EdgeDictionary
  * https://localhost:8443/DataWave/Query/listQueryLogic
  * https://localhost:8443/DataWave/Security/User/listEffectiveAuthorizations
  * https://localhost:8443/DataWave/Security/Admin/Credentials/listDNs

The response was simply 'forbidden'.

**Comment by keith-ratcliffe** [comment]
Is this still an issue for you?
If so, were these tests performed with a browser? Was the testUser.p12 client cert imported? Cert and password info can be found in the 'PKI Notes' section of the quickstart readme, if still needed

**Comment by medined** [comment]
Yes, this is still an issue.

Yes, I used a browser to visit those web pages. The Firefox browser ran from the computer running the docker container.

The testUser.p12 cert does exist inside the container at the following location which seems to match the information in the PKI section of the contrib/datawave-quickstart/README.md file.

```
/opt/datawave/web-services/deploy/application/src/main/wildfly/overlay/standalone/configuration/certificates/testUser.p12
```

For completeness, here is the output when I start the container:

```
$ ./docker-run-example.sh 1.0.0-SNAPSHOT -it
DataWave Source Home: /opt/datawave
DataWave Deploy Home: /opt/datawave/contrib/datawave-quickstart
This script is Deprecated. Instead use start-dfs.sh and start-yarn.sh
18/02/28 14:39:29 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Starting namenodes on [localhost]
localhost: starting namenode, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/hadoop-root-namenode-56003790266c.out
localhost: starting datanode, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/hadoop-root-datanode-56003790266c.out
Starting secondary namenodes [0.0.0.0]
0.0.0.0: starting secondarynamenode, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/hadoop-root-secondarynamenode-56003790266c.out
18/02/28 14:39:44 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
starting yarn daemons
starting resourcemanager, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/yarn-root-resourcemanager-56003790266c.out
localhost: starting nodemanager, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/yarn-root-nodemanager-56003790266c.out
starting historyserver, logging to /opt/datawave/contrib/datawave-quickstart/hadoop/logs/mapred-root-historyserver-56003790266c.out

[DW-INFO] - For detailed status visit 'http://localhost:50070/dfshealth.html#tab-overview' in your browser
18/02/28 14:39:48 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Safe mode is OFF
JMX enabled by default
Using config: /opt/datawave/contrib/datawave-quickstart/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED

Starting monitor on 0.0.0.0
Starting tablet servers .... done
Starting tserver on localhost
2018-02-28 14:40:12,148 [conf.ConfigSanityCheck] WARN : Use of instance.dfs.uri and instance.dfs.dir are deprecated. Consider using instance.volumes instead.
2018-02-28 14:40:12,430 [util.NativeCodeLoader] WARN : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2018-02-28 14:40:13,102 [server.Accumulo] INFO : Attempting to talk to zookeeper
2018-02-28 14:40:13,238 [server.Accumulo] INFO : ZooKeeper connected and initialized, attempting to talk to HDFS
2018-02-28 14:40:13,346 [server.Accumulo] INFO : Connected to HDFS
Starting master on localhost
Starting gc on localhost
Starting tracer on localhost

[DW-INFO] - For detailed status visit 'http://localhost:9995' in your browser
[DW-INFO] - Starting Wildfly
[DW-INFO] - Polling for EAR deployment status every 4 seconds (15 attempts max)
    -- Wildfly process not found (1/15)
    +- Wildfly up (2351). EAR deployment pending (2/15)
    +- Wildfly up (2351). EAR deployment pending (3/15)
    ++ DataWave Web successfully deployed (4/15)

[DW-INFO] - Documentation: https://localhost:8443/DataWave/doc
[DW-INFO] - Data Dictionary: https://localhost:8443/DataWave/DataDictionary
```

**Comment by keith-ratcliffe** [comment]
Your deployment looks good, but the PKI setup for the Wildfly requires two-way authentication, so the testUser.p12 client certificate just needs to be imported into your browser. I'll update the README to be a little more clear on that point

**Comment by keith-ratcliffe** [comment]
README updated. Let me know if you still have an issue after importing the certificate into your browser

**Comment by medined** [comment]
I am failing to import the p12 file into Firefox. To debug the issue, I tried to list the information inside the p12 file. I am getting an invalid password message. Should the following commands work?

```
$ cd services/common/src/main/resources
$ openssl pkcs12 -info -in testUser.p12 -passin pass:secret
MAC Iteration 2048
Mac verify error: invalid password?
```

**Comment by keith-ratcliffe** [comment]
Ahh, that's the wrong copy. The one you want is the one that's linked in the readme....
web-services/deploy/application/src/main/wildfly/overlay/standalone/configuration/certificates/testUser.p12

**Comment by medined** [comment]
When I import the correct file, the five links work. Thanks.
