### ISSUE TITLE
Run spotbugs-maven-plugin during the build

### ISSUE THREAD

**Issue by ctubbsii** [NationalSecurityAgency/datawave#376]
spotbugs-maven-plugin should be run during the build to catch potential bugs on every build

spotbugs provides an annotation to suppress triage'd false positives with a description; this should be used to incrementally fix/triage all the issues found, so the build will run with zero spotbugs issues found.

**Comment by davewichers** [comment]
Make sure you use the FindSecBugs plugin to SpotBugs when you do this. SpotBugs doesn't find many security issues. FindSecBugs does a much better, but not a great, job at that. But better than nothing. This is the same combo of free tools that GitLab uses for Java per: https://docs.gitlab.com/ee/user/application_security/sast/index.html
