### ISSUE TITLE
ThreadedRangeBundlerIterator needs a unit test

### ISSUE THREAD

**Issue by apmoriarty** [NationalSecurityAgency/datawave#390]
The ThreadedRangeBundlerIterator is a critical piece of code that needs unit tests.

**Comment by lbschanno** [comment]
Is there a list of requirements or additional documentation about this class? It's unclear exactly which test cases need to be verified from simply reading the code itself.

**Comment by apmoriarty** [comment]
Hi @lbschanno,

I should have closed this issue a while ago, my apologies. 

At one point there was an attempt to bundle document ranges together prior to execution on a tablet server, this would in effect reduce the resources consumed by executing the query. However, this feature has been off by default for years and I'm not sure it's worth investing time to test it now.

With that in mind, the ThreadedRangeBundlerIterater is essentially a ThreadedRangeBroker that sits on a the blocking queue of query plans. This functionality is covered in other unit and integration tests. I'm in favor of closing this issue, but I'll let others chime in.

**Comment by lbschanno** [comment]
@apmoriarty okay, no worries. I'll look at other tickets.
