### ISSUE TITLE
Missing scrips from datawave/tree/master/web-services/examples/http-client

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#392]
The  README.txt file at https://github.com/NationalSecurityAgency/datawave/tree/master/web-services/examples/http-client referenced bin/jaxbQuery.sh and bin/jacksonQuery.sh but they are not in the repos.  I would love to run these examples.  Where can I find these files

**Comment by brianloss** [comment]
Looks like a bad `.gitignore` file caused the initial commit of the scripts to be ignored. Added back in, and fixed some other deprecation issues in the example.
