### ISSUE TITLE
modify bash quickstart status functions to display more information

### ISSUE THREAD

**Issue by bmwmaestoso** [NationalSecurityAgency/datawave#405]
The current [**service**]Status methods all just print out pids. Sometimes there are processes that are not running and this really doesn't provide this information. For instance hadoop currently displays the following:

$ hadoopStatus
Hadoop is running. PIDs: 15508 15749 15931 16067 16314

It would be nice if the out displayed the following:
$ hadoopStatus
======  Hadoop Status  ======
RUNNING: NodeManager => 16067
RUNNING: SecondaryNameNode => 15749
RUNNING: DataNode => 15508
RUNNING: JobHistoryServer => 16314
RUNNING: ResourceManager => 15931
ERROR: hadoop name node is not running

**Comment by ivakegg** [comment]
@bmwmaestoso I am assigning this to somebody else.  Do you have a branch of work that can be used as a starting point?

**Comment by bmwmaestoso** [comment]
I thought I had submitted a PR for everything I was working on. I do have a branch that has the changes for this.

branch
https://github.com/bmwmaestoso/datawave/tree/service-status-405/contrib/datawave-quickstart

diffs
https://github.com/NationalSecurityAgency/datawave/compare/master...bmwmaestoso:service-status-405

**Comment by keith-ratcliffe** [comment]
@bmwmaestoso , pretty sure the work your describing was already merged.
E.g., see [accumulo/bootstrap.sh](https://github.com/NationalSecurityAgency/datawave/blob/master/contrib/datawave-quickstart/bin/services/accumulo/bootstrap.sh#L142) and [hadoop/bootstrap.sh](https://github.com/NationalSecurityAgency/datawave/blob/master/contrib/datawave-quickstart/bin/services/hadoop/bootstrap.sh#L118)
