### ISSUE TITLE
Remove usages of junit TemporaryFolder to prevent random test failures

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#427]
The latest release of junit's TemporaryFolder has a bug where two tests run in parallel may reference the same folder.  This occasionally causes test failures because one test will delete the shared folder before the other test finished.  We should move away from usage of TemporaryFolder until junit releases a fixed version.  

junit tracked this issue using the following ticket:
https://github.com/junit-team/junit4/issues/1223

**Comment by jzgithub1** [comment]
I will get on this if the JUnit4 project has not fixed it the underlying issue yet.  I asked them on their thread.

**Comment by brianloss** [comment]
The problem is that junit 4.13, which is where that issue is fixed, has not been released yet--it's only in beta.

**Comment by jzgithub1** [comment]
So do we want to switch to using  Files.createTempDirectory' temporarily as suggested in the JUnit ticket?

**Comment by jwomeara** [comment]
Looks like this is fixed.  Closing.

**Comment by jwomeara** [comment]
It looks like some new usages of TemporaryFolder have been added since this ticket was closed.  Can we go through and remove these usages again since they are known to cause random test failures?

**Comment by jwomeara** [comment]
@lbschanno if you have time, I noticed that some of the usages were introduced in some tests you added.  I need to do a better job of getting the word out about TemporaryFolder's concurrency issues, but if you have some time, would you be willing to check this out?

**Comment by lbschanno** [comment]
@jwomeara are you still seeing the issues when building in parallel? I ask because this ticket mentions that the bug was fixed in 4.13 (which was in beta when this ticket was originally created), and we're now using 4.13.1. I checked the source code for TemporaryFolder, and can confirm that it includes the changes from https://github.com/junit-team/junit4/pull/1304.

**Comment by jwomeara** [comment]
Oh, well if that's the case, please disregard.  I should have checked the version we're using before reopening.
