### ISSUE TITLE
Enable text wrap on the Data Dictionary page for long field names

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#475]
The field names could potentially get very long.  It is requested that the data dictionary page allows the field names to wrap.

**Comment by jzgithub1** [comment]
I am implementing the solution in this link:
[https://stackoverflow.com/questions/1057574/html-td-wrap-text](url) 

table{
    table-layout: fixed;
}

td{
    word-wrap:break-word
}

I have modified the two screen.css files that I think get jared but there are many files with that name in the project tree and some have identical content.  When I build datawave and the services i can't see the changes I made.  

I will keep on this.

**Comment by jzgithub1** [comment]
Checked in pull request:
[https://github.com/NationalSecurityAgency/datawave/pull/509](url)

**Comment by jzgithub1** [comment]
@ivakegg  and @brianloss  , What I want to try is adding this javascript code below to the 'document.ready function hard coded in the DATA_TABLES_TEMPLATE string in the declaration below:
```$("td").css("word-wrap", "break-word");```

The 'css' function is part of Jquery and should just effect this webpage.   
 
```-java
private static final String DATA_TABLES_TEMPLATE = "<script type=''text/javascript'' src=''{0}jquery.min.js''></script>\n"
                    + "<script type=''text/javascript'' src=''{1}jquery.dataTables.min.js''></script>\n" + "<script type=''text/javascript''>\n"
                    + "$(document).ready(function() '{' $(''#myTable'').dataTable('{'\"bPaginate\": false, \"aaSorting\": [[0, \"asc\"]], \"bStateSave\": true'}'); $(\"td\").css(\"word-wrap\", \"break-word\"); '}')\n"
                    + "</script>\n";
```

This will isolate the word wrapping to cells in this page hopefully.

**Comment by jzgithub1** [comment]
So the last comment did not work in this case but it is a good technique for applying styles to elements dynamically in others.  The browser transforms the word-wrap: break-word to:
```html
<td style="overflow-wrap: break-word;"></td>
```

**Comment by brianloss** [comment]
Use the [datatables API](https://datatables.net/reference/option/columns.className) to add a class name to the column(s) to be wrapped. Then modify the `screen.css` file to style td elements having the class. For example, if you called the class "wrap-text", then the style would be something like:
```
td.wrap-text {
  word-wrap: break-word;
}
```
This way anywhere in the app we wanted this kind of wrapping on table cells, we'd just have to apply the class to the desired cells.

**Comment by jzgithub1** [comment]
Thanks for the information @brianloss

**Comment by jzgithub1** [comment]
Still working this issue and I tried this but it doesn't work: 

```html
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/><title>DATAWAVE - Data Dictionary</title><link rel='stylesheet' type='text/css' href='/dictionary/css/screen.css' media='screen' />

<STYLE>
td.wrap-text {
 word-wrap: break-word;
}
 </STYLE>
<script type='text/javascript' src='/dictionary/webjars/jquery/jquery.min.js'></script>
<script type='text/javascript' src='/dictionary/webjars/datatables/js/jquery.dataTables.min.js'></script>
<script type='text/javascript'>
$(document).ready(function() { 
$('#myTable').dataTable({"columnDefs":[ { className: "td.wrap-text", "targets": [ 0 ] } ] ,  "bPaginate": false, "aaSorting": [[0, "asc"]], "bStateSave": true) }; })
</script>
</head><body>.........................................
```

**Comment by kevinrr888** [comment]
Ticket already done.
