### ISSUE TITLE
Add search to the model pages

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#481]
The query model page needs a search box just like we have in the data dictionary page.

**Comment by jzgithub1** [comment]
In progress.  

Modifying getMainContent code in ModelList.java and it is tricky to get it working right.  
`@Override
    public String getMainContent() {
        StringBuilder builder = new StringBuilder();
        
        if (this.getNames() == null || this.getNames().isEmpty()) {
            builder.append("No models available.");
        } else {
            builder.append("<div>\n");
            builder.append(" <div id=\"myTable_wrapper\" class=\"dataTables_wrapper no-footer\">\n");
            builder.append("    <div id=\"myTable_filter\" class=\"dataTables_filter\"><label>Search:<input type=\"search\"");
            builder.append("       class=\"placeholder=\" aria-controls=\"myTable\"></label>");
            builder.append("     </div>\n");
            builder.append("  <table id=\"myTable\" class=\"dataTable no-footer\" role=\"grid\" aria-describedby=\"myTable_info\">\n");
            int x = 0;
            for (String name : this.getNames()) {
                // highlight alternating rows
                if (x % 2 == 0) {
                    builder.append("<tr class=\"highlight\">");
                } else {
                    builder.append("    <tr>");
                }
                x++;
                builder.append("      <td><a href=\"/DataWave/Model/").append(name).append("\">").append(name).append("</a></td>");
                builder.append("    </tr>\n");
            }
            
            builder.append("  </table>\n");
            builder.append("  <div class=\"dataTables_info\" id=\"myTable_info\" role=\"status\" aria-live=\"polite\"></div>\n");
            builder.append("  </div>\n");
            builder.append("</div>");
        }
        return builder.toString();`

**Comment by jzgithub1** [comment]
I have this running correctly but only when I hard code the URLs to the jquery.min.js and jquery.dataTables.min.js and have the DataDictionary service running.  Look at the DATA_TABLES_TEMPLATE variable in the class listing below.   

Any ideas would be appreciated. 

CODE LISTING OF ModelList.java starts below:

`package datawave.webservice.model;

import java.io.Serializable;
import java.text.MessageFormat;
import java.util.HashSet;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import datawave.webservice.HtmlProvider;
import datawave.webservice.result.BaseResponse;

@XmlRootElement(name = "ModelList")
public class ModelList extends BaseResponse implements Serializable, HtmlProvider {
    
    private static final long serialVersionUID = 1L;
    private static final String TITLE = "Model Names", EMPTY = "";
    private static final String DATA_TABLES_TEMPLATE = "<script type=''text/javascript'' src=''https://localhost:8843/dictionary/webjars/jquery/jquery.min.js''></script>\n"
                    + "<script type=''text/javascript'' src=''https://localhost:8843/dictionary/webjars/datatables/js/jquery.dataTables.min.js''></script>\n"
                    + "<script type=''text/javascript''>\n"
                    + "$(document).ready(function() '{' $(''#myTable'').dataTable('{'\"bPaginate\": false, \"aaSorting\": [[0, \"asc\"]], \"bStateSave\": true'}') '}')\n"
                    + "</script>\n";
    
    @XmlElementWrapper(name = "ModelNames")
    @XmlElement(name = "ModelName")
    private HashSet<String> names = null;
    
    public HashSet<String> getNames() {
        return names;
    }
    
    public void setNames(HashSet<String> names) {
        this.names = names;
    }
    
    /*
     * (non-Javadoc)
     * 
     * @see datawave.webservice.HtmlProvider#getTitle()
     */
    @Override
    public String getTitle() {
        return TITLE;
    }
    
    /*
     * (non-Javadoc)
     * 
     * @see datawave.webservice.HtmlProvider#getPageHeader()
     */
    @Override
    public String getPageHeader() {
        return getTitle();
    }
    
    /*
     * (non-Javadoc)
     * 
     * @see datawave.webservice.HtmlProvider#getHeadContent()
     */
    @Override
    public String getHeadContent() {
        return DATA_TABLES_TEMPLATE;
    }
    
    /*
     * (non-Javadoc)
     * 
     * @see datawave.webservice.HtmlProvider#getMainContent()
     */
    @Override
    public String getMainContent() {
        StringBuilder builder = new StringBuilder();
        
        if (this.getNames() == null || this.getNames().isEmpty()) {
            builder.append("No models available.");
        } else {
            builder.append("<div>\n");
            builder.append("<div id=\"myTable_wrapper\" class=\"dataTables_wrapper no-footer\">\n");
            builder.append("<table id=\"myTable\" class=\"dataTable no-footer\" role=\"grid\" aria-describedby=\"myTable_info\">\n");
            builder.append("<thead><tr><th>Model Name</th></tr></thead>");
            builder.append("<tbody>");
            int x = 0;
            
            for (String name : this.getNames()) {
                // highlight alternating rows
                builder.append("<tr>");
                builder.append("<td><a href=\"/DataWave/Model/").append(name).append("?modelTableName=datawave.metadata");
                builder.append("\">").append(name).append("</a></td>");
                builder.append("</tr>\n");
            }
            builder.append("</tbody>");
            builder.append("  </table>\n");
            builder.append("  <div class=\"dataTables_info\" id=\"myTable_info\" role=\"status\" aria-live=\"polite\"></div>\n");
            builder.append("</div>\n");
            builder.append("</div>");
        }
        return builder.toString();
    }
    
}
`


I will keep experimenting on how to get the jquery stuff working without running the Dictionary Service.

**Comment by jzgithub1** [comment]
@brianloss,  do you know how I can get access to jquery.min.js and jquery.dataTables.min.js from the Model page without having the Dictionary service on and hardcoding the links?

**Comment by brianloss** [comment]
> 
> 
> @brianloss or @keith-ratcliffe: Do you know how I can get access to jquery.min.js and jquery.dataTables.min.js from the Model page without having the Dictionary service on and hardcoding the links?

Those are both added to the main web service via the web-root module. See [here](https://github.com/NationalSecurityAgency/datawave/blob/release/version2.6/web-services/web-root/pom.xml). So you should be able to use a relative path to get to them.

**Comment by jzgithub1** [comment]
@brianloss, I am not having success getting relative path to work.  In the ModelList.java class I have to hard code the paths to jquery scripts to get the search page to work.  I have tried using "/webjars/datatables/js/" and "/webjars/jquery" in the Message.Format function call in the getHeadContent function below.

```java 

private static final String DATA_TABLES_TEMPLATE = "<script type=''text/javascript'' src=''{0}jquery.min.js''></script>\n"
                    + "<script type=''text/javascript'' src=''{1}jquery.dataTables.min.js''></script>\n"
                    + "<script type=''text/javascript''>\n"
                    + "$(document).ready(function() '{' $(''#myTable'').dataTable('{'\"bPaginate\": false, \"aaSorting\": [[0, \"asc\"]], \"bStateSave\": true'}') '}')\n"
                    + "</script>\n";


  @Override
    public String getHeadContent() {
        String dataTablesHeader = MessageFormat.format(DATA_TABLES_TEMPLATE, "https://localhost:8843/dictionary/webjars/jquery/",
                        "https://localhost:8843/dictionary/webjars/datatables/js/");
        return dataTablesHeader;
    }

**Comment by brianloss** [comment]
You're trying to render content for the ModelBean, which runs in the wildfly web service, but trying to have it get static assets from the dictionary microservice. Don't do that. The code I sent is dependencies for the wildfly web service, which means you should be able to access the static assets vi the URL "/". For example, the URI for jquery.min.js should be "/jquery.min.js" and for datatables is "/jquery.dataTables.min.js".

**Comment by jzgithub1** [comment]
Thanks.  Those are the paths I did not try!
