### ISSUE TITLE
APPLICATION FAILED TO START server.outboundSsl properties

### ISSUE THREAD

**Issue by rqualis-altamiracorp** [NationalSecurityAgency/datawave#492]
I tried to start the authentication microservice and get the following error before it fails.  I am trying to use the remote auth, so set security.use.remoteauthservice=true.  Not sure why I need server.outboundSsl.  Can I turn this off; and if yes how? Started with java -jar ${DATAWAVE_SERVICES_HOME}/authorization-service*-exec.jar --spring.profiles.active=dev,nomessaging --spring.main.allow-bean-definition-overriding=true --debug=true

:

2019-07-10 12:02:19.091 ERROR 26094 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'server' to datawave.microservice.config.web.DatawaveServerProperties failed:

    Property: server.outboundSsl.trustStorePassword
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

    Property: server.outboundSsl.keyStore
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

    Property: server.outboundSsl.keyStorePassword
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

    Property: server.outboundSsl.trustStoreType
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

    Property: server.outboundSsl.keyStoreType
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

    Property: server.outboundSsl.trustStore
    Value: null
    Reason: {NotBlankIfFieldEquals.message}

Action:

Update your application's configuration

**Comment by rqualis-altamiracorp** [comment]
To troubleshoot this, I added the following to application-dev.yml

  outbound-ssl:
    trust-store: 'classpath:/testCA.p12'
    trust-store-type: PKCS12
    trust-store-password: 'ChangeIt'
    key-store: 'classpath:/testServer.p12'
    key-store-type: PKCS12
    key-store-password: 'ChangeIt'

and then restart the config service and then try to start the auth service and got the following:

2019-07-10 15:42:27.387 ERROR 27494 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in datawave.microservice.authorization.userdetails.ProxiedEntityUserDetailsService required a bean of type 'datawave.security.authorization.DatawaveUserService' that could not be found.


Action:

Consider defining a bean of type 'datawave.security.authorization.DatawaveUserService' in your configuration.

**Comment by keith-ratcliffe** [comment]
The auth service requires that a bean of type DatawaveUserService be injected. Above, you started the service without activating the 'mock' profile, so I'm assuming that you are intending to implement a different user service(?), in which case you are on the hook to configure/inject your own DatawaveUserService impl, in the same (or similar) way that was done by the mock profile example.

**Comment by rqualis-altamiracorp** [comment]
I did try including the mock as below:

java -jar ${DATAWAVE_SERVICES_HOME}/authorization-service*-exec.jar --spring.profiles.active=dev,nomessaging,mock --spring.main.allow-bean-definition-overriding=true --debug=true

**Comment by keith-ratcliffe** [comment]
The stock configs for this are known to work as currently documented, so if you've deviated very far from that in your dev environment, then it's very difficult to say what's going on without more details. All the issues you've raised are the result of bad spring configuration, but there's no way to know what you've changed and for what reason

**Comment by rqualis-altamiracorp** [comment]
I am not deploying it as a DW Quickstart as that is not what we would like.  I built it using the following command: mvn -Pdev,exec,examples -Dservices -Ddeploy -Dtar -Ddist -DskipTests clean install.  I have my instance of Hadoop, Zookeeper, Acaumulo, MySQL and WildFly installed.  I fired them all up.  I then start the config service and now need to start my auth service.  Once these are all started, then I will start WildFly since the ear file was deployed to it.  I then will try and do an ingest and a query before I move forward.  Please let me know if this is sufficient information; you help is appreciated.

**Comment by keith-ratcliffe** [comment]
We do want to help whenever we can, but I guess the bottom line is that these are dev-ops issues that can't be easily and reliably addressed here. This channel is really only intended for tracking software defects and software enhancements.

Given that you have a custom deployment environment with unspecified requirements, I am not sure this is the best place to get the level of support that is required. For example, there's just no way for us to know how you arrived at your current runtime configuration. And it's not possible for us to give advice on whether enabling/disabling SSL for your auth service is appropriate.

Generally speaking, to assist with an error that you're observing, that'll require that we have *at least* enough information to be able to reproduce the same error on our end. So, it's likely we'd need to see all your application configs & startup commands, know about any relevant software customizations that you've made, and to see any related logging output

As a rule, we can't really advise that folks post that kind of information here, because there could be sensitive information that would be inappropriate to share, and also because we're not well situated to provide dev-ops support from here

**Comment by rqualis-altamiracorp** [comment]
I totally understand.  Yes, sharing config files here would not be something I can do.
What are the options available to us to get the help under the circumstances you described?

Thanks

**Comment by rqualis-altamiracorp** [comment]
I was able to resolve the issue.  

However, for future, can you still let me know what are the options available to us to get the help under the circumstances you described.

**Comment by keith-ratcliffe** [comment]
Closing this, given that there is no software defect for us to address
