### ISSUE TITLE
come up with a way to make certain queries survive web server restarts

### ISSUE THREAD

**Issue by brianloss** [NationalSecurityAgency/datawave#5]
With the current query API, it can be problematic to restart a web server during a long-running query since either the query will be cancelled and the user has to start over, or we must wait a long time for the query to complete before shutting the server down. The latter also requires load balancer support to ensure that requests for an active query go to the draining server, but no other new requests go to it.

Design and implement a mechanism to checkpoint query progress so that a server can be restarted between next calls without interrupting the query. This could be supported only for certain query logics at first, although it would be nice to have it for all query logics.

**Comment by phrocker** [comment]
I really like this idea. Taking the scan session and keeping that stored somewhere is a great idea. You lose context of the current scansession or multiscansession, but that lost state shouldn't be devastating. What data source were you thinking of using to store the scan session progress/info?

**Comment by brianloss** [comment]
I hadn't really thought through it yet. @ivakegg and I were discussing a bit yesterday, and this would help with several pain points if we could come up with at least something better than what we have now. We were talking about basically saving the last returned key from each of the scanners (and not using batch scanners on the client side, but replacing with our own version of them so we could then keep the ranges necessary). Maybe that would have to be the last key returned at the end of the previous next call. As for where to store, we didn't discuss. Could use something like redis, or since there's already a Hazelcast cache cluster set up for the microservices, maybe that could be used for storing the state.

**Comment by phrocker** [comment]
Yeah I agree that's a useful feature. You could control it so that losing many webservers at once doesn't mean we have a 're-query storm' but I like the idea. If you can store all ranges and queries produced you could potentially not have to re-query the index, depending on where the index lookup is. That may be too complicated since this could be a big win without that.

**Comment by ivakegg** [comment]
This is covered under the query microservices work: #1026
