### ISSUE TITLE
Java 11 Migration

### ISSUE THREAD

**Issue by milleruntime** [NationalSecurityAgency/datawave#510]
Ticket for java 11 migration. Accumulo 2.0 will work with Java 11 so as a first step, it would be good to start migrating Maven plugins over.  Here are a few good links for Java 11 migration:

https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

I am working on updating Datawave's maven plugins and hope to have a PR up soon.

**Comment by drewfarris** [comment]
@milleruntime - this issue is a little old, any additional progress?

Is anyone else actively working on this?

**Comment by brianloss** [comment]
@drewfarris I did a bunch of work to get everything running on Accumulo 2.0 and update to use Accumulo 2 APIs pretty much everywhere I could find. That's in the `feature/accumulo-2.0` branch. Ivan and I had been merging into that branch regularly, but looks like nothing's been done in about a month and the build failed for the last merge in. Nevertheless, this branch would be the best starting point for JDK 11 work.

**Comment by milleruntime** [comment]
@drewfarris this ticket could be closed since it is very broad.  @brianloss took over where I left off so his comments reflect the most up to date work done. #533 could be used for work to be done on the ```feature/accumulo-2.0``` branch.
