### ISSUE TITLE
Unique and Groupby functions should work with fields starting with $

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#550]
Currently users must put a $ in front of fields that start with a numeric.  This is a result of using Jexl as the underlying query language in which field names cannot start with a numeric.  However the functions that take in fields lists currently do not have that requirement and in fact will fail to do what the users wants if they do add $ in from of fields names starting with a numeric.  These functions should be able to handle the fields in a consistent manner.

**Comment by jwomeara** [comment]
good to me, this looks!
