### ISSUE TITLE
Error Events with timestamp of zero dropped

### ISSUE THREAD

**Issue by bbux-atg** [NationalSecurityAgency/datawave#594]
If there is a problem with parsing the date of an event, it may get populated with a date of zero along with an error such as EVENT_DATE_MISSING. In the [EventMapper#L460](https://github.com/NationalSecurityAgency/datawave/blob/f2d133e581abcd1dad7808d1c9a3792cf152eddc/warehouse/ingest-core/src/main/java/datawave/ingest/mapreduce/EventMapper.java#L460) if the Event date is less than the discard interval, the Event is dropped.  Thus the Error Events do not make it into any configured Error Tables.  It would be helpful to only drop non Error Events or provide an option to not drop them.

**Comment by ivakegg** [comment]
Are you working this one Brian?

**Comment by bbux-atg** [comment]
Resolved with https://github.com/NationalSecurityAgency/datawave/pull/595
