### ISSUE TITLE
Docker container thread count too low

### ISSUE THREAD

**Issue by Mahedros** [NationalSecurityAgency/datawave#672]
I'm attempting to run the quickstart docker container and I'm encountering a problem when `datawaveWebStart` attempts to deploy the EAR. 

The following error appears in datawave-quickstart/wildfly/standalone/log/server.log:

    2019-12-06 13:01:47,184 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 48) WFLYCTL0013: Operation ("add") failed - address: ([
        ("subsystem" => "ee"),
        ("managed-executor-service" => "default")
    ]) - failure description: "WFLYEE00113: The max-threads value 48 cannot be less than the core-threads value 64."

Since I haven't seen any mention of this issue elsewhere I'm inclined to believe it's a problem specific to our system, so I'm curious if there's a recommended way to fix this that wouldn't require changes to the source.

**Comment by keith-ratcliffe** [comment]
Since core-threads is system dependent, there's an environment variable for the quickstart that you can use to override the max-threads value for Wildfly in this case....

Prior to running the Docker image build script, ensure that the following is set in your bash session
```
export DW_WILDFLY_EE_DEFAULT_MAX_THREADS=64
```
Or whatever value you want

**Comment by keith-ratcliffe** [comment]
My original assumption was that you were getting this error while building the quickstart Docker image. If instead you're getting the error with a Docker image that was already built successfully, then you can just edit this file inside the running container:
```
/opt/datawave/contrib/datawave-quickstart/bin/services/datawave/wildfly-install/standalone/configuration/standalone-full.xml
```
Edit this line
```
...
<managed-executor-service name="default" jndi-name="java:jboss/ee/concurrency/executor/default" context-service="default" hung-task-threshold="60000" max-threads="48" keepalive-time="5000"/>
...
```
Then start Wildfly (_datawaveWebStart_)

**Comment by Mahedros** [comment]
I had modified standalone-full.xml, but I didn't want to have to keep doing it every time I started a new container so I was looking into my options for a more long-term solution. Setting the environment variable seems like a better option to me.
