### ISSUE TITLE
We need a simple query UI

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#703]
The DATAWAVE quickstart should also stand up a simple UI through which a user can send a query and get the results.  I expect the use case would be something like this:

1) enter query and parameters and hit submit button -> returns a page containing the query plan and a next button
2) hit next button -> returns a page containing a page of results and a next button
3) repeat 2 until there are no more results in which case you get a close button

**Comment by jzgithub1** [comment]
I will get working on this.
