### ISSUE TITLE
#UNIQUE by minute, hour, or day

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#711]
The #UNIQUE will allow unique results by a set of fields.  However some fields (such as a datetime field) could use further granularity within the #UNIQUE function.  For example one may want a unique result for every hour of the day (e.g. #UNIQUE(HOUR(datetime_field)) or something like that.

**Comment by lbschanno** [comment]
@ivakegg I'm interested in working on this. What class contains the logic for the #UNIQUE function?
