### ISSUE TITLE
Add ability to use the field index value for custom filtering

### ISSUE THREAD

**Issue by jwomeara** [NationalSecurityAgency/datawave#8]
Need to add support for populating the value cell of the field index filter with relevant data, and to add support for filtering against that data at query time within the query iterators.

**Comment by phrocker** [comment]
Interesting. Are you talking about something that survives only the query or aggregating data?

**Comment by jwomeara** [comment]
The idea is to selectively add data to the field index value at ingest time, so that we can do a quick filter evaluation when we're scanning the field index.  

For instance, if we know that we see queries of the form #INTERSECTS(WKT_FIELD, "some wkt") AND WKT_BYTE_LENGTH: [0 to 50]

In that case, it would be convenient to store the WKT_BYTE_LENGTH for a given document in the field index value for the WKT_FIELD so that we can quickly determine whether the WKT_BYTE_LENGTH falls within the given range, without having to do the full Jexl evaluation on the entire document.  Hopefully this will speed up queries of that nature by filtering results out a little earlier.

**Comment by phrocker** [comment]
@jwomeara I'm thinking more about this, and am wondering about your example. You're effectively creating a composite index in the value of an FI key. Why not use composite indices? You can do the same thing after you've expanded the functions into index lookups, but before it begins interrogating shards.

**Comment by jwomeara** [comment]
@ivakegg and I talked about this a bit in the early stages, but at the time, I think we had some reservations.  Looking back on it now, (with a bit more understanding of the underlying code on my part) and talking through it this morning, I think we may revisit this idea.  Thanks, dude!

**Comment by ivakegg** [comment]
@phrocker There were several reasons we did not go with the compound index to start with:

1) The compound index for two terms currently cannot handle a intersecting a range for each term.  This implementation can handle a range or regex for the first term and then an arbitrary function on the second one.
2) The compound index currently does not handle searches on only the primary (first) term.  You still have to index the primary term separately.

Now that being said, perhaps we need to step back and see whether we can modify the compound index to be able to handle the additional functionality.
