### ISSUE TITLE
quickstart build fails

### ISSUE THREAD

**Issue by szemicael** [NationalSecurityAgency/datawave#805]
In release/version 2.10, when running env.sh:
[ERROR] Failed to execute goal on project datawave-ws-security: Could not resolve dependencies for project gov.nsa.datawave.webservices:datawave-ws-security:ejb:2.10.0-SNAPSHOT: Could not transfer artifact javax.transaction:jta:jar:1.0.1B from/to boundless (https://repo.boundlessgeo.com/main/): repo.boundlessgeo.com: Unknown host repo.boundlessgeo.com -> [Help 1]
Appears repo at https://repo.boundlessgeo.com/main/ no longer exists.
Replacing repo with https://repo.osgeo.org/repository/release/ in main pom.xml fixed the issue.

**Comment by keith-ratcliffe** [comment]
Reopening temporarily until dd04d37 is backported to other branches. Noticed PR builds for 2.7 and 2.8 were failing due to the same problem
