### ISSUE TITLE
Backport `osgeo` update to other branches

### ISSUE THREAD

**Issue by drewfarris** [NationalSecurityAgency/datawave#812]
We likely need to backport the fix from #806 adfde5a to more than just the  `master` branch, possibly `2.7`, `2.8` and `2.9` but likely also `hadoop3` and `accumulo-2.0` branches as well.

**Comment by keith-ratcliffe** [comment]
I backported to 2.7, 2.8, and 2.9 already. Hadoop3 and accumulo-2.0 seem to have it as well, so thinking we can probably close this one

**Comment by drewfarris** [comment]
Cool, thanks @keith-ratcliffe
