### ISSUE TITLE
Active query log should handle multiple tables separately

### ISSUE THREAD

**Issue by ivakegg** [NationalSecurityAgency/datawave#817]
The Active query log should track queries separately against the shard, errorShard, and queryMetricsE tables.

**Comment by lbschanno** [comment]
Per discussion with @ivakegg:
- Include the table name in the Active query log for the shard, errorShard, and queryMetricsE tables.
- Assign each of the tables above their own Active query log instance.

**Comment by lbschanno** [comment]
Per discussion with @ivakegg for a design:
- Add a query option called `active.query.log.name` which will be used in lieu of a table name. This will allow the client to use the table name or query logic name.
- In `ShardQueryLogic`, configure a property to use the table name, query logic name, or nothing for this option.
- Have a cache of `ActiveQueryLog` instances. When a value is specified for `active.query.log.name`, retrieve or create a new `ActiveQueryLog` instance for that value, and use it for the associated `QueryIterator`. Additionally, ensure that the name value is included in log messages.
- If no value is specified for `active.query.name`, use a default `ActiveQueryLog` instance that may be shared among multiple `QueryIterator` instances.
