### ISSUE TITLE
LookupTermsFromRegex incorrectly checks exceeded value threshold

### ISSUE THREAD

**Issue by FineAndDandy** [NationalSecurityAgency/datawave#826]
The iterator will continue to run until it times out or exhausts all keys

**Comment by keith-ratcliffe** [comment]
Interesting. Related to #824 possibly

**Comment by FineAndDandy** [comment]
I don't think so, but possible. I think this is more an efficiency issue. There is a single batch scanner created and because its over the entire range of the regex you don't know if there will be another field encountered that matches that hasn't yet exceeded the value key. If there is more than one field there is no short-cutting even if all possible fields have exceeded values, unless the max unfielded expansion threshold is reached. The penalty for going over all keys is bounded by the timeout, so it may not be worth fixing.

**Comment by FineAndDandy** [comment]
An interesting idea here would be to have accumulo allow updates to the column families between batches for the underlying scans. As we hit value limits on a field we could remove that column family from the batch. Which would cause updates to the range bounds (potentially) and no longer include these results in returned batches.
