### ISSUE TITLE
QueryModelVisitor returns unflattened script

### ISSUE THREAD

**Issue by apmoriarty** [NationalSecurityAgency/datawave#898]
Specifically in the case of a bounded range.

Suppose a model contains a mapping like FIELD -> {A, B}

For query
`(FIELD > '2' && FIELD < '5')`

Expands to
`(A > '2' && A < '5') || (B > '2' && B < '5')`   <--- The backing jexl script is not flattened.

**Comment by ivakegg** [comment]
I believe bounded ranges are supposed to stay bounded which is to say they remain within a reference expression (parens).  I do not agree with this issue.

**Comment by ivakegg** [comment]
@apmoriarty Is there a reason that I am unaware of that this should be done?

**Comment by apmoriarty** [comment]
Sorry for the delay, here are some examples...

Case of expanding a bounded range
```
Original Script: FOO > 'a' && FOO < 'z'
Expanded Script: ((BAR1 < 'z' && BAR1 > 'a') || (BAR2 < 'z' && BAR2 > 'a'))
Expanded & Flat: ((BAR1 < 'z' && BAR1 > 'a') || (BAR2 < 'z' && BAR2 > 'a'))
Expanded[counts { and: 3, or: 1}] Flattened[counts { and: 2, or: 1}]
```

Case of null in query
```
Original Script: FOO1 == 'baz' && FOO1 == null
Expanded Script: ($1BAR == 'baz' || $2BAR == 'baz') && ($1BAR == null && $2BAR == null)
Expanded & Flat: ($1BAR == 'baz' || $2BAR == 'baz') && $1BAR == null && $2BAR == null
Expanded[counts { and: 2, or: 1}] Flattened[counts { and: 1, or: 1}]
```

Case of multi term OR where each term has multiple expansion
```
Original Script: FOO == 'baz' || FOO2 == 'baz'
Expanded Script: (BAR2 == 'baz' || BAR1 == 'baz' || BAR3 == 'baz') || (BAR22 == 'baz' || BAR23 == 'baz')
Expanded & Flat: BAR2 == 'baz' || BAR1 == 'baz' || BAR3 == 'baz' || BAR22 == 'baz' || BAR23 == 'baz'
Expanded[counts { and: 0, or: 3}] Flattened[counts { and: 0, or: 1}]
```
