### ISSUE TITLE
Incorrect Query Plan for Mulitple Ranges

### ISSUE THREAD

**Issue by hayreg** [NationalSecurityAgency/datawave#902]
When multiple ranges for the same field are AND'd together, all but the last range is omitted from the query plan. All the ranges are present in the query plan when OR'd together. This is occurring for a specific field however is probably a general issue. This was observed in DW 2.5.26.

It is believed that the omission is occurring somewhere in the DefaultQueryPlanner class.

**Comment by ivakegg** [comment]
It appears that the "coalescing of ranges" stage puts all of the comparison nodes for the same field into the same reference expression and then a stage down the line presumes that the range contains only two nodes and drops the other two.  What needs to happen is that the coalescing of ranges ensures that each range has only two sides and that any existing parens are kept as appropriate.
