### ISSUE TITLE
PointType and GeometryType should implement sizeInBytes method to avoid NoSuchMethodException in ObjectSizeOf

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#911]
Using jstack, we observed lots of NoSuchMethodException's being thrown on tservers, on the reflective invocation of `sizeInBytes` inside ObjectSizeOf.java (L116).

Debugging revealed that the issue was that our `PointType` class doesn't implement the method. It falls back on the BaseType impl, causing the code to recurse the object graph, throwing additional NoSuchMethodException along the way. 

```
ObjectSizeOf {
   ....
               if (useSizeInBytesMethod) {
                            try {
                                if (o instanceof ObjectSizeOf) {
                                    size = ((ObjectSizeOf) o).sizeInBytes();
                                } else {
Line 116 >>                 Method sizeInBytes = o.getClass().getMethod("sizeInBytes", (Class<?>[]) null);
                                    size = (Long) sizeInBytes.invoke(o);
                                }
                            } catch (Throwable t) {
                                // ok, lets do this the hard way...
                            }
                        }
                        if (size == 0) {
                            // the hard way...
                            // do not include Class related objects or reflection objects
```

**Comment by jwomeara** [comment]
Working through this.  It might take a bit of time to do as there are many different types of geometries which need to be accounted for.

**Comment by jwomeara** [comment]
WIP over here: https://github.com/NationalSecurityAgency/datawave-type-utils/tree/geometryTypeSize

**Comment by keith-ratcliffe** [comment]
Given the relatively high complexity of geo types, compared to our other types, and given that the main thing we want to avoid is repeatedly cascading NSME's, I'm wondering what you guys think about just enabling some sort of simple caching mechanism in ObjectSizeOf that would allow us to avoid the getMethod("sizeInBytes",...) call entirely, if we've already stumbled on NSME at least once for the given class. Something like...
```
private static ConcurrentHashSet<String> noSizeInBytesImpl ..; 
```
...could do the trick. Populate it in the catch block, and interrogate it prior to the getMethod call

Spring's ReflectionUtils class uses a similar strategy for stuff like this, which is what made me think of it.

Or is it still better to avoid "do it the hard way" path if at all possible?

**Comment by jwomeara** [comment]
I think I have the sizeInBytes method worked out for the point and geometry types - it's definitely more of an art than a science.  I added a test which demonstrates that the estimated sizes are within 5% of the actual sizes.  I feel pretty good about that going forward.

PR here: https://github.com/NationalSecurityAgency/datawave-type-utils/pull/5/files

**Comment by keith-ratcliffe** [comment]
Fix merged in https://github.com/NationalSecurityAgency/datawave-type-utils/pull/5
