### ISSUE TITLE
Consider alternate Datawave Quickstart Initialization Strategy

### ISSUE THREAD

**Issue by drewfarris** [NationalSecurityAgency/datawave#913]
The current Quickstart documentation encourages users to add the following to their `.bashrc`:

```
export DW_SOURCE='/path/to/datawave'
source ${DW_SOURCE}/contrib/datawave-quickstart/bin/env.sh
```

The quickstart `env.sh` kicks off a bunch of things, some of which aren't particularly sensitive to what else is going on with a machine. For example, if I have one terminal that's in the middle of a `datawaveBuildDeploy` and I open another terminal, all sorts of bad things may happen.

As a result, I've taken to adding the following to my `.bashrc` as an alternative:

```
enableQuickstart() {
  export DW_SOURCE='/path/to/datawave'
  source ${DW_SOURCE}/contrib/datawave-quickstart/bin/env.sh
}
```

At the cost of remembering to run this, I can optionally setup the Datawave Quickstart environment for any given shell.

**Comment by foster33** [comment]
This seems to have been implemented. Current documentation suggests to do the following: 
`echo -e "activateDW() {\n source DW_SOURCE/contrib/datawave-quickstart/bin/env.sh\n}" >> ~/.bashrc`
