### ISSUE TITLE
ObjectSizeOf$Sizer should minimize occurrence of NoSuchMethodException

### ISSUE THREAD

**Issue by keith-ratcliffe** [NationalSecurityAgency/datawave#915]
ObjectSizeOf$Sizer invokes `sizeInBytes` reflectively on objects in order to calculate size. This can flood the tserver JVM with NSME's whenever BaseType's `sizeInBytes` implementation is used, as it computes the size of the internal `delegate` instance recursively using further reflection. Those exceptions are swallowed, but they can still incur significant cost in the tserver as we've observed during testing/debugging

ObjectSizeOf$Sizer could mitigate 99.999% of that cost by leveraging a simple, thread-safe caching strategy, in order to avoid the `sizeInBytes` invocation on classes already known to have thrown an NSME previously

re: #911

**Comment by lbschanno** [comment]
@keith-ratcliffe please close this ticket since it has been fixed by your PR.
