### ISSUE TITLE
AnyFieldQueryTest is failing 

### ISSUE THREAD

**Issue by friedlou** [NationalSecurityAgency/datawave#931]
[ERROR] Tests run: 27, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 45.893 s <<< FAILURE! - in datawave.query.AnyFieldQueryTest
[ERROR] testOrOr(datawave.query.AnyFieldQueryTest)  Time elapsed: 0.052 s  <<< FAILURE!
org.junit.ComparisonFailure: Did not find a matching child for OrNode in [OrNode]: Num children differ: [EQNode, EQNode, EQNode] vs [EQNode, EQNode, EQNode, EQNode] expected:<...ATE == 'mississippi'[]> but was:<...ATE == 'mississippi'[ || _NOFIELD_ == 'none']>
        at datawave.query.AnyFieldQueryTest.testOrOr(AnyFieldQueryTest.java:287)

**Comment by ivakegg** [comment]
Are you sure you don't have the latest code update?

**Comment by ivakegg** [comment]
Works on my machine
